// GENERATED by tool/gen_owned_gear_grips.py — do not hand-edit.
// Weapons: handle (bbox bottom). Shields/frills: bbox center.

import 'dart:ui' show Offset;

/// Per-[visualSetId] grip points for owned hand items on the paper-doll.
abstract final class OwnedGearGrips {
  static const Map<String, Offset> byVisualSetId = {
    'axe_bloodhowl': Offset(0.6914, 0.8594),
    'axe_goreblade': Offset(0.6992, 0.8750),
    'axe_t0': Offset(0.7500, 0.8047),
    'bow_eagle': Offset(0.6133, 0.6875),
    'bow_t0': Offset(0.7266, 0.8828),
    'bow_windpierce': Offset(0.6133, 0.7031),
    'dagger_nightbite': Offset(0.7070, 0.8125),
    'dagger_shadowfang': Offset(0.7070, 0.7812),
    'dagger_t0': Offset(0.7500, 0.7969),
    'frill_prism': Offset(0.2578, 0.6484),
    'frill_soulcodex': Offset(0.2578, 0.6484),
    'frill_t0': Offset(0.2578, 0.6484),
    'mace_dawnbreak': Offset(0.6914, 0.8438),
    'mace_lightbringer': Offset(0.6914, 0.8281),
    'mace_t0': Offset(0.7500, 0.7969),
    'shield_aegis': Offset(0.5664, 0.5352),
    'shield_ironwall': Offset(0.5664, 0.5273),
    'shield_t0': Offset(0.2578, 0.6484),
    'staff_frostfire': Offset(0.7188, 0.8359),
    'staff_nethercore': Offset(0.7266, 0.8516),
    'staff_t0': Offset(0.7578, 0.7266),
    'sword_runebound': Offset(0.7031, 0.8516),
    'sword_t0': Offset(0.7031, 0.8516),
    'sword_thunderfury': Offset(0.6875, 0.8203),
    'sword_warglaive': Offset(0.5898, 0.8359),
  };

  static const Offset mainHandFallback = Offset(0.75, 0.82);
  static const Offset offHandFallback = Offset(0.26, 0.65);

  static Offset forVisualSetId(
    String visualSetId, {
    required bool offHand,
  }) {
    final hit = byVisualSetId[visualSetId];
    if (hit != null) return hit;
    return offHand ? offHandFallback : mainHandFallback;
  }

  static String? visualSetIdFromAsset(String assetPath) {
    final name = assetPath.split('/').last;
    for (final suffix in ['_idle.png', '_walk.png', '_attack.png']) {
      if (name.endsWith(suffix)) {
        return name.substring(0, name.length - suffix.length);
      }
    }
    return null;
  }

  static Offset forAsset(String assetPath, {required bool offHand}) {
    final id = visualSetIdFromAsset(assetPath);
    if (id == null) {
      return offHand ? offHandFallback : mainHandFallback;
    }
    return forVisualSetId(id, offHand: offHand);
  }
}
