// GENERATED by tool/gen_owned_gear_grips.py — do not hand-edit.
// Grip: that weapon's hold, on an opaque pixel. The butt hangs past it.
// Rest: clockwise radians so a blade points up and out.
// restOff aims the same art up and out from the left hand.

import 'dart:ui' show Offset;

/// Per-[visualSetId] grip points for owned hand items on the paper-doll.
abstract final class OwnedGearGrips {
  static const Map<String, Offset> byVisualSetId = {
    'axe_bloodhowl': Offset(0.7500, 0.7109),
    'axe_goreblade': Offset(0.7500, 0.7109),
    'axe_stormcleave': Offset(0.7578, 0.7031),
    'axe_t0': Offset(0.7500, 0.7109),
    'bow_ashflight': Offset(0.7500, 0.5078),
    'bow_eagle': Offset(0.7500, 0.5078),
    'bow_t0': Offset(0.7500, 0.5078),
    'bow_windpierce': Offset(0.7500, 0.5078),
    'crossbow_t0': Offset(0.6406, 0.7422),
    'dagger_nightbite': Offset(0.7344, 0.7031),
    'dagger_shadowfang': Offset(0.7344, 0.6953),
    'dagger_t0': Offset(0.7344, 0.7031),
    'dagger_venomkiss': Offset(0.7344, 0.7109),
    'fist_t0': Offset(0.5625, 0.6172),
    'frill_embercodex': Offset(0.1875, 0.5859),
    'frill_prism': Offset(0.1562, 0.5859),
    'frill_soulcodex': Offset(0.2500, 0.5859),
    'frill_t0': Offset(0.1875, 0.5859),
    'gun_t0': Offset(0.6484, 0.6797),
    'mace_dawnbreak': Offset(0.6953, 0.6641),
    'mace_lightbringer': Offset(0.7031, 0.6562),
    'mace_soulhammer': Offset(0.7109, 0.6719),
    'mace_t0': Offset(0.7109, 0.6719),
    'polearm_t0': Offset(0.7500, 0.6484),
    'shield_aegis': Offset(0.2188, 0.4922),
    'shield_frostwall': Offset(0.2188, 0.5078),
    'shield_ironwall': Offset(0.2188, 0.4766),
    'shield_t0': Offset(0.2188, 0.4766),
    'staff_frostfire': Offset(0.7344, 0.6094),
    'staff_nethercore': Offset(0.7500, 0.6328),
    'staff_t0': Offset(0.7578, 0.6094),
    'staff_voidspire': Offset(0.7266, 0.6094),
    'sword_emberfang': Offset(0.7422, 0.6797),
    'sword_runebound': Offset(0.7422, 0.6797),
    'sword_t0': Offset(0.7422, 0.6797),
    'sword_thunderfury': Offset(0.7422, 0.6797),
    'sword_warglaive': Offset(0.7578, 0.6719),
    'thrown_t0': Offset(0.5000, 0.6719),
    'wand_t0': Offset(0.7188, 0.6094),
  };

  static const Map<String, double> restByVisualSetId = {
    'axe_bloodhowl': 1.1098,
    'axe_goreblade': 1.1098,
    'axe_stormcleave': 0.9820,
    'axe_t0': 1.1098,
    'bow_ashflight': 0.5896,
    'bow_eagle': 0.4161,
    'bow_t0': 0.5896,
    'bow_windpierce': 0.5896,
    'crossbow_t0': 2.5547,
    'dagger_nightbite': 1.1659,
    'dagger_shadowfang': 1.0116,
    'dagger_t0': 1.1659,
    'dagger_venomkiss': 1.1415,
    'fist_t0': 0.0000,
    'frill_embercodex': 0.0000,
    'frill_prism': 0.0000,
    'frill_soulcodex': 0.0000,
    'frill_t0': 0.0000,
    'gun_t0': 2.5378,
    'mace_dawnbreak': 1.1409,
    'mace_lightbringer': 1.1043,
    'mace_soulhammer': 1.0993,
    'mace_t0': 1.0993,
    'polearm_t0': 0.1194,
    'shield_aegis': 0.0000,
    'shield_frostwall': 0.0000,
    'shield_ironwall': 0.0000,
    'shield_t0': 0.0000,
    'staff_frostfire': 0.1818,
    'staff_nethercore': 0.1348,
    'staff_t0': 0.1038,
    'staff_voidspire': 0.2613,
    'sword_emberfang': 1.1289,
    'sword_runebound': 1.1289,
    'sword_t0': 1.1289,
    'sword_thunderfury': 1.1289,
    'sword_warglaive': 1.0532,
    'thrown_t0': 0.0000,
    'wand_t0': 1.0501,
  };

  static const Map<String, double> restOffByVisualSetId = {
    'axe_bloodhowl': 0.3488,
    'axe_goreblade': 0.3488,
    'axe_stormcleave': 0.2209,
    'axe_t0': 0.3488,
    'bow_ashflight': -0.4161,
    'bow_eagle': -0.5896,
    'bow_t0': -0.4161,
    'bow_windpierce': -0.4161,
    'crossbow_t0': -0.4273,
    'dagger_nightbite': 0.4049,
    'dagger_shadowfang': 0.2506,
    'dagger_t0': 0.4049,
    'dagger_venomkiss': 0.3805,
    'fist_t0': 0.0000,
    'frill_embercodex': 0.0000,
    'frill_prism': 0.0000,
    'frill_soulcodex': 0.0000,
    'frill_t0': 0.0000,
    'gun_t0': -0.4441,
    'mace_dawnbreak': 0.3799,
    'mace_lightbringer': 0.3432,
    'mace_soulhammer': 0.3383,
    'mace_t0': 0.3383,
    'polearm_t0': -0.1194,
    'shield_aegis': 0.0000,
    'shield_frostwall': 0.0000,
    'shield_ironwall': 0.0000,
    'shield_t0': 0.0000,
    'staff_frostfire': -0.0570,
    'staff_nethercore': -0.1040,
    'staff_t0': -0.1351,
    'staff_voidspire': 0.0225,
    'sword_emberfang': 0.3679,
    'sword_runebound': 0.3679,
    'sword_t0': 0.3679,
    'sword_thunderfury': 0.3679,
    'sword_warglaive': 0.2922,
    'thrown_t0': 0.0000,
    'wand_t0': 0.2891,
  };

  static const Offset mainHandFallback = Offset(0.75, 0.82);
  static const Offset offHandFallback = Offset(0.26, 0.65);

  static Offset forVisualSetId(
    String visualSetId, {
    required bool offHand,
  }) {
    final hit = byVisualSetId[visualSetId];
    if (hit != null) return hit;
    return offHand ? offHandFallback : mainHandFallback;
  }

  static String? visualSetIdFromAsset(String assetPath) {
    final name = assetPath.split('/').last;
    for (final suffix in ['_idle.png', '_walk.png', '_attack.png']) {
      if (name.endsWith(suffix)) {
        return name.substring(0, name.length - suffix.length);
      }
    }
    return null;
  }

  static Offset forAsset(String assetPath, {required bool offHand}) {
    final id = visualSetIdFromAsset(assetPath);
    if (id == null) {
      return offHand ? offHandFallback : mainHandFallback;
    }
    return forVisualSetId(id, offHand: offHand);
  }

  /// Idle twist added on top of the hand anchor's swing.
  static double restForAsset(
    String assetPath, {
    required bool offHand,
  }) {
    final id = visualSetIdFromAsset(assetPath);
    if (id == null) return 0;
    final map = offHand ? restOffByVisualSetId : restByVisualSetId;
    return map[id] ?? 0;
  }
}
