// GENERATED by tool/gen_owned_gear_grips.py — do not hand-edit.
// Weapons: handle-pixel centroid. Shields/frills: shape centroid.
// Always an opaque pixel, so the hand never grabs empty air.

import 'dart:ui' show Offset;

/// Per-[visualSetId] grip points for owned hand items on the paper-doll.
abstract final class OwnedGearGrips {
  static const Map<String, Offset> byVisualSetId = {
    'axe_bloodhowl': Offset(0.7818, 0.7464),
    'axe_goreblade': Offset(0.7818, 0.7464),
    'axe_stormcleave': Offset(0.7818, 0.7464),
    'axe_t0': Offset(0.7818, 0.7464),
    'bow_ashflight': Offset(0.6406, 0.4844),
    'bow_eagle': Offset(0.6406, 0.4844),
    'bow_t0': Offset(0.6406, 0.4844),
    'bow_windpierce': Offset(0.6415, 0.4922),
    'crossbow_t0': Offset(0.6880, 0.7633),
    'dagger_nightbite': Offset(0.7379, 0.7071),
    'dagger_shadowfang': Offset(0.7500, 0.7109),
    'dagger_t0': Offset(0.7437, 0.7126),
    'dagger_venomkiss': Offset(0.7385, 0.7078),
    'fist_t0': Offset(0.5581, 0.6124),
    'frill_embercodex': Offset(0.1875, 0.7094),
    'frill_prism': Offset(0.2079, 0.7236),
    'frill_soulcodex': Offset(0.2539, 0.7227),
    'frill_t0': Offset(0.1914, 0.7227),
    'gun_t0': Offset(0.7029, 0.7149),
    'mace_dawnbreak': Offset(0.7775, 0.7464),
    'mace_lightbringer': Offset(0.7693, 0.7395),
    'mace_soulhammer': Offset(0.7818, 0.7464),
    'mace_t0': Offset(0.7818, 0.7464),
    'polearm_t0': Offset(0.7500, 0.8353),
    'shield_aegis': Offset(0.2150, 0.5822),
    'shield_frostwall': Offset(0.2148, 0.6348),
    'shield_ironwall': Offset(0.2159, 0.5864),
    'shield_t0': Offset(0.2188, 0.6406),
    'staff_frostfire': Offset(0.7373, 0.8295),
    'staff_nethercore': Offset(0.7367, 0.8607),
    'staff_t0': Offset(0.7373, 0.8295),
    'staff_voidspire': Offset(0.7373, 0.8295),
    'sword_emberfang': Offset(0.8080, 0.7453),
    'sword_runebound': Offset(0.7928, 0.7393),
    'sword_t0': Offset(0.8008, 0.7424),
    'sword_thunderfury': Offset(0.8078, 0.7453),
    'sword_warglaive': Offset(0.8088, 0.7464),
    'thrown_t0': Offset(0.5000, 0.7416),
    'wand_t0': Offset(0.8027, 0.7045),
  };

  static const Offset mainHandFallback = Offset(0.75, 0.82);
  static const Offset offHandFallback = Offset(0.26, 0.65);

  static Offset forVisualSetId(
    String visualSetId, {
    required bool offHand,
  }) {
    final hit = byVisualSetId[visualSetId];
    if (hit != null) return hit;
    return offHand ? offHandFallback : mainHandFallback;
  }

  static String? visualSetIdFromAsset(String assetPath) {
    final name = assetPath.split('/').last;
    for (final suffix in ['_idle.png', '_walk.png', '_attack.png']) {
      if (name.endsWith(suffix)) {
        return name.substring(0, name.length - suffix.length);
      }
    }
    return null;
  }

  static Offset forAsset(String assetPath, {required bool offHand}) {
    final id = visualSetIdFromAsset(assetPath);
    if (id == null) {
      return offHand ? offHandFallback : mainHandFallback;
    }
    return forVisualSetId(id, offHand: offHand);
  }
}
