// GENERATED by tool/gen_owned_glove_tips.py — do not hand-edit.
// Extra shift from the bare fist to the outer rim of a worn glove.
// Missing key means the glove already ends on the fist.

import 'dart:ui' show Offset;

import 'body_family.dart';
import 'owned_gear_grips.dart';

/// Where a worn glove sticks out past the skin hand.
abstract final class OwnedGloveTips {
  static const Map<String, Offset> mainByKey = {
    'warrior/hands_broad': Offset(0.0426, -0.0036),
    'warrior/hands_leather_broad': Offset(-0.1605, -0.0026),
    'warrior/hands_leather_short': Offset(-0.1168, 0.0000),
    'warrior/hands_leather_t0': Offset(-0.1683, -0.0026),
    'warrior/hands_leather_t2': Offset(-0.1605, 0.0003),
    'warrior/hands_short': Offset(-0.0379, 0.0000),
    'warrior/hands_t0': Offset(0.0426, -0.0036),
    'warrior/hands_t2': Offset(0.0504, 0.0003),
    'rogue/hands_broad': Offset(0.2476, 0.0248),
    'rogue/hands_mail_broad': Offset(0.0439, -0.0097),
    'rogue/hands_mail_short': Offset(-0.0080, -0.0012),
    'rogue/hands_mail_t0': Offset(-0.0018, 0.0329),
    'rogue/hands_mail_t2': Offset(0.0626, 0.0000),
    'rogue/hands_short': Offset(0.0862, -0.0004),
    'rogue/hands_t0': Offset(0.1706, 0.0000),
    'rogue/hands_t2': Offset(0.2662, 0.0000),
    'mage/hands_broad': Offset(0.2653, 0.0000),
    'mage/hands_leather_broad': Offset(0.0810, 0.0112),
    'mage/hands_leather_short': Offset(0.0722, 0.0356),
    'mage/hands_leather_t0': Offset(0.0880, 0.0000),
    'mage/hands_leather_t2': Offset(0.1111, 0.0000),
    'mage/hands_mail_broad': Offset(0.0810, 0.0112),
    'mage/hands_mail_short': Offset(0.0722, 0.0356),
    'mage/hands_mail_t0': Offset(0.0880, 0.0000),
    'mage/hands_mail_t2': Offset(0.1111, 0.0000),
    'mage/hands_short': Offset(0.1337, 0.0405),
    'mage/hands_t0': Offset(0.2361, 0.0000),
    'mage/hands_t2': Offset(0.2519, 0.0000),
    'healer/hands_broad': Offset(0.2587, 0.0442),
    'healer/hands_leather_broad': Offset(0.0738, 0.0416),
    'healer/hands_leather_short': Offset(0.0926, 0.0154),
    'healer/hands_leather_t0': Offset(0.0999, 0.0000),
    'healer/hands_leather_t2': Offset(0.0998, 0.0390),
    'healer/hands_mail_broad': Offset(0.0738, 0.0416),
    'healer/hands_mail_short': Offset(0.0926, 0.0154),
    'healer/hands_mail_t0': Offset(0.0999, 0.0000),
    'healer/hands_mail_t2': Offset(0.0998, 0.0390),
    'healer/hands_plate_broad': Offset(0.0972, 0.0416),
    'healer/hands_plate_short': Offset(0.1395, 0.0154),
    'healer/hands_plate_t0': Offset(0.1234, 0.0000),
    'healer/hands_plate_t2': Offset(0.1232, 0.0390),
    'healer/hands_short': Offset(0.1392, 0.0174),
    'healer/hands_t0': Offset(0.2637, 0.0000),
    'healer/hands_t2': Offset(0.2587, 0.0442),
  };

  static const Map<String, Offset> offByKey = {
    'warrior/hands_broad': Offset(-0.0348, -0.0022),
    'warrior/hands_leather_broad': Offset(0.1762, -0.0064),
    'warrior/hands_leather_short': Offset(0.1153, 0.0000),
    'warrior/hands_leather_t0': Offset(0.1918, -0.0096),
    'warrior/hands_leather_t2': Offset(0.1918, -0.0085),
    'warrior/hands_short': Offset(0.0000, 0.0000),
    'warrior/hands_t0': Offset(-0.0348, -0.0022),
    'warrior/hands_t2': Offset(-0.0504, -0.0048),
    'rogue/hands_broad': Offset(-0.2431, 0.0198),
    'rogue/hands_mail_broad': Offset(-0.0368, -0.0004),
    'rogue/hands_mail_short': Offset(0.0165, 0.0032),
    'rogue/hands_mail_t0': Offset(0.0000, 0.0000),
    'rogue/hands_mail_t2': Offset(-0.0301, 0.0000),
    'rogue/hands_short': Offset(-0.0695, 0.0050),
    'rogue/hands_t0': Offset(-0.1579, 0.0060),
    'rogue/hands_t2': Offset(-0.2104, 0.0000),
    'mage/hands_broad': Offset(-0.2382, 0.0162),
    'mage/hands_leather_broad': Offset(-0.0572, 0.0198),
    'mage/hands_leather_short': Offset(-0.0365, 0.0173),
    'mage/hands_leather_t0': Offset(-0.0681, 0.0000),
    'mage/hands_leather_t2': Offset(-0.0898, 0.0371),
    'mage/hands_mail_broad': Offset(-0.0572, 0.0198),
    'mage/hands_mail_short': Offset(-0.0365, 0.0173),
    'mage/hands_mail_t0': Offset(-0.0681, 0.0000),
    'mage/hands_mail_t2': Offset(-0.0898, 0.0371),
    'mage/hands_short': Offset(-0.0992, 0.0164),
    'mage/hands_t0': Offset(-0.2018, 0.0384),
    'mage/hands_t2': Offset(-0.2389, 0.0403),
    'healer/hands_broad': Offset(-0.2418, 0.0394),
    'healer/hands_leather_broad': Offset(-0.0621, 0.0394),
    'healer/hands_leather_short': Offset(-0.0738, 0.0167),
    'healer/hands_leather_t0': Offset(-0.0893, 0.0000),
    'healer/hands_leather_t2': Offset(-0.0907, 0.0346),
    'healer/hands_mail_broad': Offset(-0.0621, 0.0394),
    'healer/hands_mail_short': Offset(-0.0738, 0.0167),
    'healer/hands_mail_t0': Offset(-0.0893, 0.0000),
    'healer/hands_mail_t2': Offset(-0.0907, 0.0346),
    'healer/hands_plate_broad': Offset(-0.0855, 0.0394),
    'healer/hands_plate_short': Offset(-0.1210, 0.0136),
    'healer/hands_plate_t0': Offset(-0.1049, 0.0000),
    'healer/hands_plate_t2': Offset(-0.1141, 0.0346),
    'healer/hands_short': Offset(-0.1213, 0.0172),
    'healer/hands_t0': Offset(-0.2465, 0.0000),
    'healer/hands_t2': Offset(-0.2555, 0.0452),
  };

  /// Fractions of the 128 sprite. Add to the skin fist.
  static Offset shiftFor(
    String? assetPath,
    BodyFamily? family, {
    required bool offHand,
  }) {
    if (assetPath == null || family == null) return Offset.zero;
    final id = OwnedGearGrips.visualSetIdFromAsset(assetPath);
    if (id == null) return Offset.zero;
    final map = offHand ? offByKey : mainByKey;
    return map['${family.name}/$id'] ?? Offset.zero;
  }
}
