// GENERATED by tool/gen_owned_glove_tips.py — do not hand-edit.
// Extra shift from the bare fist into the palm of a worn glove.
// Missing key means the glove already ends on the fist.

import 'dart:ui' show Offset;

import 'body_family.dart';
import 'owned_gear_grips.dart';

/// Where the weapon crosses the palm of a worn glove.
abstract final class OwnedGloveTips {
  static const Map<String, Offset> mainByKey = {
    'warrior/hands_broad': Offset(0.1388, 0.1388),
    'warrior/hands_leather_broad': Offset(-0.0634, 0.1452),
    'warrior/hands_leather_short': Offset(-0.0538, 0.0528),
    'warrior/hands_leather_t0': Offset(-0.0653, 0.1420),
    'warrior/hands_leather_t2': Offset(-0.0566, 0.1592),
    'warrior/hands_short': Offset(0.0306, 0.0581),
    'warrior/hands_t0': Offset(0.1457, 0.1385),
    'warrior/hands_t2': Offset(0.1503, 0.1489),
    'rogue/hands_broad': Offset(0.1633, 0.1716),
    'rogue/hands_mail_broad': Offset(-0.0359, 0.1487),
    'rogue/hands_mail_short': Offset(-0.0851, 0.0618),
    'rogue/hands_mail_t0': Offset(-0.0923, 0.1772),
    'rogue/hands_mail_t2': Offset(-0.0364, 0.2379),
    'rogue/hands_short': Offset(0.0130, 0.0589),
    'rogue/hands_t0': Offset(0.0991, 0.1618),
    'rogue/hands_t2': Offset(0.1578, 0.2223),
    'mage/hands_broad': Offset(0.1699, 0.2004),
    'mage/hands_leather_broad': Offset(-0.0085, 0.2082),
    'mage/hands_leather_short': Offset(-0.0338, 0.0953),
    'mage/hands_leather_t0': Offset(-0.0317, 0.1689),
    'mage/hands_leather_t2': Offset(-0.0171, 0.1894),
    'mage/hands_mail_broad': Offset(-0.0085, 0.2082),
    'mage/hands_mail_short': Offset(-0.0338, 0.0953),
    'mage/hands_mail_t0': Offset(-0.0317, 0.1689),
    'mage/hands_mail_t2': Offset(-0.0171, 0.1894),
    'mage/hands_short': Offset(0.0279, 0.0978),
    'mage/hands_t0': Offset(0.1246, 0.1618),
    'mage/hands_t2': Offset(0.1298, 0.1768),
    'healer/hands_broad': Offset(0.1582, 0.1621),
    'healer/hands_leather_broad': Offset(-0.0252, 0.1746),
    'healer/hands_leather_short': Offset(-0.0199, 0.0553),
    'healer/hands_leather_t0': Offset(-0.0359, 0.1398),
    'healer/hands_leather_t2': Offset(-0.0253, 0.1676),
    'healer/hands_mail_broad': Offset(-0.0252, 0.1746),
    'healer/hands_mail_short': Offset(-0.0199, 0.0553),
    'healer/hands_mail_t0': Offset(-0.0359, 0.1398),
    'healer/hands_mail_t2': Offset(-0.0253, 0.1676),
    'healer/hands_plate_broad': Offset(-0.0017, 0.1746),
    'healer/hands_plate_short': Offset(0.0269, 0.0553),
    'healer/hands_plate_t0': Offset(-0.0125, 0.1398),
    'healer/hands_plate_t2': Offset(-0.0075, 0.1700),
    'healer/hands_short': Offset(0.0306, 0.0530),
    'healer/hands_t0': Offset(0.1264, 0.1356),
    'healer/hands_t2': Offset(0.1257, 0.1541),
  };

  static const Map<String, Offset> offByKey = {
    'warrior/hands_broad': Offset(-0.1277, 0.1427),
    'warrior/hands_leather_broad': Offset(0.0723, 0.1329),
    'warrior/hands_leather_short': Offset(0.0578, 0.0067),
    'warrior/hands_leather_t0': Offset(0.0742, 0.1219),
    'warrior/hands_leather_t2': Offset(0.0610, 0.1030),
    'warrior/hands_short': Offset(-0.0666, 0.0168),
    'warrior/hands_t0': Offset(-0.1396, 0.1419),
    'warrior/hands_t2': Offset(-0.1411, 0.1415),
    'rogue/hands_broad': Offset(-0.1517, 0.1637),
    'rogue/hands_mail_broad': Offset(0.0416, 0.1146),
    'rogue/hands_mail_short': Offset(0.0915, 0.0554),
    'rogue/hands_mail_t0': Offset(0.0993, 0.1623),
    'rogue/hands_mail_t2': Offset(0.0816, 0.1812),
    'rogue/hands_short': Offset(-0.0002, 0.0515),
    'rogue/hands_t0': Offset(-0.0976, 0.1649),
    'rogue/hands_t2': Offset(-0.1013, 0.1663),
    'mage/hands_broad': Offset(-0.1491, 0.1573),
    'mage/hands_leather_broad': Offset(0.0378, 0.1680),
    'mage/hands_leather_short': Offset(0.0653, 0.0762),
    'mage/hands_leather_t0': Offset(0.0534, 0.1264),
    'mage/hands_leather_t2': Offset(0.0406, 0.1357),
    'mage/hands_mail_broad': Offset(0.0378, 0.1680),
    'mage/hands_mail_short': Offset(0.0653, 0.0762),
    'mage/hands_mail_t0': Offset(0.0534, 0.1264),
    'mage/hands_mail_t2': Offset(0.0406, 0.1357),
    'mage/hands_short': Offset(-0.0033, 0.0693),
    'mage/hands_t0': Offset(-0.0964, 0.1188),
    'mage/hands_t2': Offset(-0.1115, 0.1249),
    'healer/hands_broad': Offset(-0.1421, 0.1669),
    'healer/hands_leather_broad': Offset(0.0377, 0.1786),
    'healer/hands_leather_short': Offset(0.0354, 0.0565),
    'healer/hands_leather_t0': Offset(0.0453, 0.1426),
    'healer/hands_leather_t2': Offset(0.0335, 0.1574),
    'healer/hands_mail_broad': Offset(0.0377, 0.1786),
    'healer/hands_mail_short': Offset(0.0354, 0.0565),
    'healer/hands_mail_t0': Offset(0.0453, 0.1426),
    'healer/hands_mail_t2': Offset(0.0335, 0.1574),
    'healer/hands_plate_broad': Offset(0.0183, 0.1789),
    'healer/hands_plate_short': Offset(-0.0115, 0.0487),
    'healer/hands_plate_t0': Offset(0.0297, 0.1426),
    'healer/hands_plate_t2': Offset(0.0161, 0.1605),
    'healer/hands_short': Offset(-0.0151, 0.0541),
    'healer/hands_t0': Offset(-0.1129, 0.1309),
    'healer/hands_t2': Offset(-0.1173, 0.1473),
  };

  /// Fractions of the 128 sprite. Add to the skin fist.
  static Offset shiftFor(
    String? assetPath,
    BodyFamily? family, {
    required bool offHand,
  }) {
    if (assetPath == null || family == null) return Offset.zero;
    final id = OwnedGearGrips.visualSetIdFromAsset(assetPath);
    if (id == null) return Offset.zero;
    final map = offHand ? offByKey : mainByKey;
    return map['${family.name}/$id'] ?? Offset.zero;
  }
}
