#!/usr/bin/env python3
"""Generate lib/visual/owned_gear_grips.dart from char/gear/*_idle.png.

Weapons: grip = bottom-center of opaque bbox (handle).
Shields/frills: grip = opaque bbox center.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
GEAR = ROOT / "assets" / "custom" / "char" / "gear"
OUT = ROOT / "lib" / "visual" / "owned_gear_grips.dart"


def grip_uv(im: Image.Image, *, off_hand: bool) -> tuple[float, float] | None:
    bbox = im.getbbox()
    if bbox is None:
        return None
    left, top, right, bottom = bbox
    cx = (left + right) / 2 / 128
    if off_hand:
        return (cx, (top + bottom) / 2 / 128)
    return (cx, max(0.0, (bottom - 5) / 128))


def main() -> None:
    lines: list[str] = [
        "// GENERATED by tool/gen_owned_gear_grips.py — do not hand-edit.",
        "// Weapons: handle (bbox bottom). Shields/frills: bbox center.",
        "",
        "import 'dart:ui' show Offset;",
        "",
        "/// Per-[visualSetId] grip points for owned hand items on the paper-doll.",
        "abstract final class OwnedGearGrips {",
        "  static const Map<String, Offset> byVisualSetId = {",
    ]

    count = 0
    for path in sorted(GEAR.glob("*_idle.png")):
        stem = path.name.removesuffix("_idle.png")
        im = Image.open(path).convert("RGBA")
        off = stem.startswith(("shield_", "frill_"))
        grip = grip_uv(im, off_hand=off)
        if grip is None:
            continue
        gx, gy = grip
        lines.append(f"    '{stem}': Offset({gx:.4f}, {gy:.4f}),")
        count += 1
        print(f"{stem:28s} grip=({gx:.3f},{gy:.3f})")

    lines.extend(
        [
            "  };",
            "",
            "  static const Offset mainHandFallback = Offset(0.75, 0.82);",
            "  static const Offset offHandFallback = Offset(0.26, 0.65);",
            "",
            "  static Offset forVisualSetId(",
            "    String visualSetId, {",
            "    required bool offHand,",
            "  }) {",
            "    final hit = byVisualSetId[visualSetId];",
            "    if (hit != null) return hit;",
            "    return offHand ? offHandFallback : mainHandFallback;",
            "  }",
            "",
            "  static String? visualSetIdFromAsset(String assetPath) {",
            "    final name = assetPath.split('/').last;",
            "    for (final suffix in ['_idle.png', '_walk.png', '_attack.png']) {",
            "      if (name.endsWith(suffix)) {",
            "        return name.substring(0, name.length - suffix.length);",
            "      }",
            "    }",
            "    return null;",
            "  }",
            "",
            "  static Offset forAsset(String assetPath, {required bool offHand}) {",
            "    final id = visualSetIdFromAsset(assetPath);",
            "    if (id == null) {",
            "      return offHand ? offHandFallback : mainHandFallback;",
            "    }",
            "    return forVisualSetId(id, offHand: offHand);",
            "  }",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {count} grips -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
