#!/usr/bin/env python3
"""Generate lib/visual/owned_gear_grips.dart from char/gear/*_idle.png.

Weapons: grip = centroid of the handle pixels (bottom of the art).
Bows, shields and frills: grip = centroid of all pixels (held mid-shape).

Both land on **opaque** pixels. A bbox center is empty air on diagonal art
(sword, bow, staff), which used to hang the weapon beside the hand.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
GEAR = ROOT / "assets" / "custom" / "char" / "gear"
OUT = ROOT / "lib" / "visual" / "owned_gear_grips.dart"
ALPHA = 40

# Handle band: bottom slice of the art the hand can close around.
HANDLE_BAND = 14


def _centroid(
    im: Image.Image, y0: int, y1: int
) -> tuple[float, float] | None:
    px = im.load()
    sx = sy = n = 0
    for y in range(max(0, y0), min(im.height, y1)):
        for x in range(im.width):
            if px[x, y][3] >= ALPHA:
                sx += x
                sy += y
                n += 1
    if n == 0:
        return None
    return (sx / n, sy / n)


def _snap_to_opaque(
    im: Image.Image, x: float, y: float
) -> tuple[float, float]:
    """Nearest opaque pixel — a centroid can still fall in a hole."""
    px = im.load()
    if px[int(x), int(y)][3] >= ALPHA:
        return (x, y)
    best = (x, y)
    best_d = None
    for yy in range(im.height):
        for xx in range(im.width):
            if px[xx, yy][3] < ALPHA:
                continue
            d = (xx - x) ** 2 + (yy - y) ** 2
            if best_d is None or d < best_d:
                best_d = d
                best = (float(xx), float(yy))
    return best


def grip_uv(
    im: Image.Image, *, off_hand: bool, mid_grip: bool = False
) -> tuple[float, float] | None:
    bbox = im.getbbox()
    if bbox is None:
        return None
    _, top, _, bottom = bbox
    if mid_grip:
        # Mass centroid drifts into a heavy bow head — use the shape's
        # mid-height row band instead so the hand sits on the middle.
        mid = (top + bottom) // 2
        point = _centroid(im, mid - 4, mid + 5) or _centroid(im, top, bottom)
    elif off_hand:
        point = _centroid(im, top, bottom)
    else:
        # Handle first; fall back to the whole shape for flat art.
        point = _centroid(im, bottom - HANDLE_BAND, bottom) or _centroid(
            im, top, bottom
        )
    if point is None:
        return None
    x, y = _snap_to_opaque(im, point[0], point[1])
    return (x / 128, y / 128)


def main() -> None:
    lines: list[str] = [
        "// GENERATED by tool/gen_owned_gear_grips.py — do not hand-edit.",
        "// Weapons: handle-pixel centroid. Shields/frills: shape centroid.",
        "// Always an opaque pixel, so the hand never grabs empty air.",
        "",
        "import 'dart:ui' show Offset;",
        "",
        "/// Per-[visualSetId] grip points for owned hand items on the paper-doll.",
        "abstract final class OwnedGearGrips {",
        "  static const Map<String, Offset> byVisualSetId = {",
    ]

    count = 0
    for path in sorted(GEAR.glob("*_idle.png")):
        stem = path.name.removesuffix("_idle.png")
        im = Image.open(path).convert("RGBA")
        off = stem.startswith(("shield_", "frill_"))
        # A bow is held at its middle, not by the lower limb.
        grip = grip_uv(im, off_hand=off, mid_grip=stem.startswith("bow_"))
        if grip is None:
            continue
        gx, gy = grip
        lines.append(f"    '{stem}': Offset({gx:.4f}, {gy:.4f}),")
        count += 1
        print(f"{stem:28s} grip=({gx:.3f},{gy:.3f})")

    lines.extend(
        [
            "  };",
            "",
            "  static const Offset mainHandFallback = Offset(0.75, 0.82);",
            "  static const Offset offHandFallback = Offset(0.26, 0.65);",
            "",
            "  static Offset forVisualSetId(",
            "    String visualSetId, {",
            "    required bool offHand,",
            "  }) {",
            "    final hit = byVisualSetId[visualSetId];",
            "    if (hit != null) return hit;",
            "    return offHand ? offHandFallback : mainHandFallback;",
            "  }",
            "",
            "  static String? visualSetIdFromAsset(String assetPath) {",
            "    final name = assetPath.split('/').last;",
            "    for (final suffix in ['_idle.png', '_walk.png', '_attack.png']) {",
            "      if (name.endsWith(suffix)) {",
            "        return name.substring(0, name.length - suffix.length);",
            "      }",
            "    }",
            "    return null;",
            "  }",
            "",
            "  static Offset forAsset(String assetPath, {required bool offHand}) {",
            "    final id = visualSetIdFromAsset(assetPath);",
            "    if (id == null) {",
            "      return offHand ? offHandFallback : mainHandFallback;",
            "    }",
            "    return forVisualSetId(id, offHand: offHand);",
            "  }",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {count} grips -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
