// Death Knight kits (Blood / Frost / Unholy)
part of '../class_ability.dart';

const List<ClassAbilityDef> _deathKnightKit = <ClassAbilityDef>[
    // —— blood ——
    ClassAbilityDef(
      id: AbilityId.bloodPresence,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Blood Presence',
      shortLabel: 'BPres',
      description: 'Always on: tankier + self-heal.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 0.98,
      passiveInMul: 0.85,
      passiveHealMul: 1.18,
    ),
    ClassAbilityDef(
      id: AbilityId.deathStrike,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Death Strike',
      shortLabel: 'DStrike',
      description: 'Strike that heals you.',
      unlockLevel: 3,
      cooldown: 5.5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.28,
    ),
    ClassAbilityDef(
      id: AbilityId.heartStrike,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Heart Strike',
      shortLabel: 'Heart',
      description: 'Heavy single-target strike.',
      unlockLevel: 5,
      cooldown: 4.5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.22,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.runeTap,
      boltStyle: SpellBoltStyle.shadow,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Rune Tap',
      shortLabel: 'Tap',
      description: 'Convert runes to self heal.',
      unlockLevel: 7,
      cooldown: 12,
      resourceCost: 10,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.45,
    ),
    ClassAbilityDef(
      id: AbilityId.bloodBoil,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Blood Boil',
      shortLabel: 'BBoil',
      description: 'AoE disease burst.',
      unlockLevel: 9,
      cooldown: 8,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.78,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFC05060,
        groundDisc: true,
        groundArgb: 0x77A03040,
        groundLife: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.deathAndDecayBlood,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Death and Decay',
      shortLabel: 'DnD',
      description: 'Shadow ground that burns the pack around you.',
      unlockLevel: 10,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.62,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8050A0,
        groundDisc: true,
        groundLife: 4.0,
        groundArgb: 0x66804090,
        groundRadius: 2.8,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.boneShield,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Bone Shield',
      shortLabel: 'BShield',
      description: 'Bone absorb shell on yourself.',
      unlockLevel: 8,
      cooldown: 18,
      resourceCost: 12,
      effect: AbilityEffectKind.absorb,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFC0B090,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.vampiricBlood,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Vampiric Blood',
      shortLabel: 'VBlood',
      description: 'Emergency max HP.',
      unlockLevel: 11,
      cooldown: 40,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.dancingRuneWeapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Dancing Rune Weapon',
      shortLabel: 'RuneW',
      description: 'Signature damage buff.',
      unlockLevel: 11,
      cooldown: 45,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFF90C0FF,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 5,
    ),
    ClassAbilityDef(
      id: AbilityId.iceboundFortitude,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Icebound Fortitude',
      shortLabel: 'B-IBF',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.darkCommand,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.blood,
      name: 'Dark Command',
      shortLabel: 'DarkC',
      description: 'Hard taunt nearest loose foe.',
      unlockLevel: 4,
      cooldown: 8,
      resourceCost: 10,
      effect: AbilityEffectKind.taunt,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8050A0,
      ),
    ),

    // —— frostDk ——
    ClassAbilityDef(
      id: AbilityId.frostPresence,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Frost Presence',
      shortLabel: 'FPres',
      description: 'Always on: frost power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 2.1,
      passiveInMul: 0.97,
    ),
    ClassAbilityDef(
      id: AbilityId.obliterate,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Obliterate',
      shortLabel: 'Obliter',
      description: 'Heavy dual strike.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 2.10,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFFA0E8FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.frostStrike,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Frost Strike',
      shortLabel: 'FrStr',
      description: 'Icy finisher.',
      unlockLevel: 5,
      cooldown: 4,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.90,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF80D0FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.howlingBlast,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Howling Blast',
      shortLabel: 'Howl',
      description: 'Frost AoE.',
      unlockLevel: 7,
      cooldown: 7,
      resourceCost: 16,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFFB8F0FF,
        groundDisc: true,
        groundArgb: 0x6690D8FF,
        groundLife: 2.2,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.chainsOfIce,
      boltStyle: SpellBoltStyle.frost,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Chains of Ice',
      shortLabel: 'Chains',
      description: 'Root nearest foe.',
      unlockLevel: 9,
      cooldown: 12,
      resourceCost: 12,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.pillarOfFrost,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Pillar of Frost',
      shortLabel: 'Pillar',
      description: 'Self damage buff.',
      unlockLevel: 11,
      cooldown: 30,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.hungeringCold,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Hungering Cold',
      shortLabel: 'HCold',
      description: 'Freeze the pack in place.',
      unlockLevel: 11,
      cooldown: 35,
      resourceCost: 25,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90D8FF,
        groundDisc: true,
        groundLife: 2.2,
        groundArgb: 0x6690D8FF,
        groundRadius: 2.8,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.frostDkIbf,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.frostDk,
      name: 'Icebound Fortitude',
      shortLabel: 'F-IBF',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— unholy ——
    ClassAbilityDef(
      id: AbilityId.unholyPresence,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Unholy Presence',
      shortLabel: 'UPres',
      description: 'Always on: haste lean.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.16,
      passiveHasteMul: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.scourgeStrike,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Scourge Strike',
      shortLabel: 'Scourge',
      description: 'Plague-powered hit.',
      unlockLevel: 3,
      cooldown: 4.5,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.12,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.deathCoil,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Death Coil',
      shortLabel: 'Coil',
      description: 'Ranged shadow bolt.',
      unlockLevel: 5,
      cooldown: 5.5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.04,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB070E0,
      ),
      castDelaySeconds: 0.35,
    ),
    ClassAbilityDef(
      id: AbilityId.bloodBoilUnholy,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Blood Boil',
      shortLabel: 'UBoil',
      description: 'AoE disease burst.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.95,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF9060A8,
        groundDisc: true,
        groundArgb: 0x66804090,
        groundLife: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.deathAndDecayUnholy,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Death and Decay',
      shortLabel: 'DnD',
      description: 'Shadow ground that burns the pack around you.',
      unlockLevel: 8,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.62,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF9060B0,
        groundDisc: true,
        groundLife: 4.0,
        groundArgb: 0x66804090,
        groundRadius: 2.8,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.gargoyle,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Summon Gargoyle',
      shortLabel: 'Garg',
      description: 'Summon a gargoyle that fights beside you.',
      unlockLevel: 9,
      cooldown: 45,
      resourceCost: 25,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFA080C0,
      ),
      summonCount: 1,
      summonDuration: 22,
      summonAtkScale: 0.48,
      summonName: 'Gargoyle',
      summonIdPrefix: 'garg',
      summonHasteSeconds: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.antiMagicShell,
      boltStyle: SpellBoltStyle.arcane,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Anti-Magic Shell',
      shortLabel: 'AMShell',
      description: 'Absorb on self.',
      unlockLevel: 11,
      cooldown: 30,
      resourceCost: 10,
      effect: AbilityEffectKind.absorb,
      tier: AbilityCastTier.filler,
      coeff: 1.0,
    ),
    ClassAbilityDef(
      id: AbilityId.armyOfDead,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Army of the Dead',
      shortLabel: 'Army',
      description: 'Summon a short-lived ghoul swarm.',
      unlockLevel: 11,
      cooldown: 50,
      resourceCost: 30,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 0.55,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF706090,
        groundDisc: true,
        groundLife: 2.5,
        groundArgb: 0x66706090,
        groundRadius: 2.6,
      ),
      summonCount: 4,
      summonDuration: 16,
      summonAtkScale: 0.30,
      summonName: 'Ghoul',
      summonIdPrefix: 'army',
      aoeShape: AbilityAoeShape.nova,
    ),
    ClassAbilityDef(
      id: AbilityId.unholyIbf,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.unholy,
      name: 'Icebound Fortitude',
      shortLabel: 'U-IBF',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
