// Druid kits (Balance / Feral / Guardian / Restoration)
part of '../class_ability.dart';

const List<ClassAbilityDef> _druidKit = <ClassAbilityDef>[
    // —— balance ——
    ClassAbilityDef(
      id: AbilityId.moonkinForm,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Moonkin Form',
      shortLabel: 'Owl',
      description: 'Always on: owlkin body — more power, thicker hide.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.16,
      passiveInMul: 0.92,
    ),
    ClassAbilityDef(
      id: AbilityId.wrath,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Wrath',
      shortLabel: 'BWrath',
      description: 'Nature bolt — arms Solar Eclipse.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      castDelaySeconds: 1.4,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF90E060,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.starfire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Starfire',
      shortLabel: 'Star',
      description: 'Heavy arcane bolt — arms Lunar Eclipse.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.45,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFD0A0FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.moonfire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Moonfire',
      shortLabel: 'Moon',
      description: 'Astral DoT hit.',
      unlockLevel: 7,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.9,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFA0C0FF,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.insectSwarm,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Insect Swarm',
      shortLabel: 'Swarm',
      description: 'Maintain a nature insect DoT on the focus.',
      unlockLevel: 7,
      cooldown: 5.5,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.72,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70C040,
      ),
      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.hurricane,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Hurricane',
      shortLabel: 'Hurric',
      description: 'AoE astral storm.',
      unlockLevel: 9,
      cooldown: 12,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.92,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D050,
        groundDisc: true,
        groundLife: 3.5,
        groundArgb: 0x6670C048,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.rain,
    ),
    ClassAbilityDef(
      id: AbilityId.typhoon,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Typhoon',
      shortLabel: 'Typhoon',
      description: 'Knock / root pulse.',
      unlockLevel: 11,
      cooldown: 16,
      resourceCost: 15,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.starfall,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Starfall',
      shortLabel: 'SFall',
      description: 'Signature AoE rain.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 30,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 1.0,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFE0C060,
        groundDisc: true,
        groundLife: 4.0,
        groundArgb: 0x77D0A040,
        groundRadius: 3.0,
      ),

      aoeShape: AbilityAoeShape.rain,
    ),
    ClassAbilityDef(
      id: AbilityId.barkskinBal,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.balance,
      name: 'Barkskin',
      shortLabel: 'Bark',
      description: 'Emergency bark — take less while low.',
      unlockLevel: 11,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— feral ——
    ClassAbilityDef(
      id: AbilityId.catForm,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Cat Form',
      shortLabel: 'Cat',
      description: 'Always on: cat body — melee haste.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.28,
      passiveHasteMul: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.shred,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Shred',
      shortLabel: 'Shred',
      description: 'Core cat strike — builds a combo point.',
      unlockLevel: 3,
      cooldown: 3.5,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
    ),
    ClassAbilityDef(
      id: AbilityId.rake,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Rake',
      shortLabel: 'Rake',
      description: 'Bleed opener — builds a combo point.',
      unlockLevel: 5,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.95,

      gate: AbilityGate(skipIfBleedAbove: 3.5),
    ),
    ClassAbilityDef(
      id: AbilityId.ferociousBite,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Ferocious Bite',
      shortLabel: 'Bite',
      description: 'Finisher bite — spends combo points for more damage.',
      unlockLevel: 7,
      cooldown: 5.5,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.5,
      gate: AbilityGate(comboMin: 1),
    ),
    ClassAbilityDef(
      id: AbilityId.tigersFury,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Tiger\'s Fury',
      shortLabel: 'TFury',
      description: 'Grant energy + buff.',
      unlockLevel: 9,
      cooldown: 18,
      effect: AbilityEffectKind.grantResource,
      tier: AbilityCastTier.filler,
      coeff: 30,
    ),
    ClassAbilityDef(
      id: AbilityId.feralSwipe,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Swipe',
      shortLabel: 'Swipe',
      description: 'Cat claw sweep — builds a combo point.',
      unlockLevel: 7,
      cooldown: 7,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.48,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFA050,
        groundDisc: true,
        groundLife: 1.5,
        groundArgb: 0x88FFE08A,
        groundRadius: 2.5,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.feralThrash,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Thrash',
      shortLabel: 'Thrash',
      description: 'Claw the pack and leave a bleed.',
      unlockLevel: 8,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.45,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF9050,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x88FFE08A,
        groundRadius: 2.5,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.berserk,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Berserk',
      shortLabel: 'Berserk',
      description: 'Signature haste window.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF8050,
      ),

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.rip,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Rip',
      shortLabel: 'Rip',
      description: 'Maintain a deep bleed on the foe.',
      unlockLevel: 11,
      cooldown: 6,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.55,

      gate: AbilityGate(skipIfBleedAbove: 2.5),
    ),
    ClassAbilityDef(
      id: AbilityId.survivalInstincts,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.feral,
      name: 'Survival Instincts',
      shortLabel: 'SurvI',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— guardian ——
    ClassAbilityDef(
      id: AbilityId.bearForm,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Bear Form',
      shortLabel: 'Bear',
      description: 'Always on: bear body — tankiness.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 0.95,
      passiveInMul: 0.88,
    ),
    ClassAbilityDef(
      id: AbilityId.mangleBear,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Mangle',
      shortLabel: 'Mangle',
      description: 'Bear swipe strike.',
      unlockLevel: 3,
      cooldown: 4.5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.swipe,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Swipe',
      shortLabel: 'Swipe',
      description: 'AoE claw.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.40,

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.guardianThrash,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Thrash',
      shortLabel: 'Thrash',
      description: 'Claw the pack and leave a bleed.',
      unlockLevel: 6,
      cooldown: 6,
      resourceCost: 16,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.62,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFC07840,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x88C07040,
        groundRadius: 2.5,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.lacerate,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Lacerate',
      shortLabel: 'Lacer',
      description: 'Maintain a bleed on your focus.',
      unlockLevel: 6,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.78,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFC07050,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.maul,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Maul',
      shortLabel: 'Maul',
      description: 'Heavy threat hit.',
      unlockLevel: 7,
      cooldown: 5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.3,
    ),
    ClassAbilityDef(
      id: AbilityId.frenziedRegen,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Frenzied Regeneration',
      shortLabel: 'Frenzy',
      description: 'Self heal.',
      unlockLevel: 9,
      cooldown: 16,
      resourceCost: 20,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.2,
    ),
    ClassAbilityDef(
      id: AbilityId.barkskinGuard,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Barkskin',
      shortLabel: 'Bark',
      description: 'Emergency DR.',
      unlockLevel: 11,
      cooldown: 40,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.berserkGuard,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Berserk',
      shortLabel: 'BearBk',
      description: 'Signature rage window.',
      unlockLevel: 11,
      cooldown: 45,
      effect: AbilityEffectKind.grantResource,
      tier: AbilityCastTier.signature,
      coeff: 40,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF8050,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.survivalInstinctsGuard,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Survival Instincts',
      shortLabel: 'Instinct',
      description: 'Emergency big DR.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.growl,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.guardian,
      name: 'Growl',
      shortLabel: 'Growl',
      description: 'Hard taunt nearest loose foe.',
      unlockLevel: 4,
      cooldown: 8,
      resourceCost: 10,
      effect: AbilityEffectKind.taunt,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFD070,
      ),
    ),

    // —— restorationDruid ——
    ClassAbilityDef(
      id: AbilityId.treeOfLife,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Tree of Life',
      shortLabel: 'Tree',
      description: 'Always on: tree body — heal amplify.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveHealMul: 1.34,
    ),
    ClassAbilityDef(
      id: AbilityId.rejuvenation,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Rejuvenation',
      shortLabel: 'Rejuv',
      description: 'HoT-style heal.',
      unlockLevel: 3,
      cooldown: 4.5,
      resourceCost: 12,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D070,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.regrowth,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Regrowth',
      shortLabel: 'Regrow',
      description: 'Fast heal.',
      unlockLevel: 5,
      cooldown: 5,
      resourceCost: 18,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.35,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF60E080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.wildGrowth,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Wild Growth',
      shortLabel: 'Growth',
      description: 'Party heal pulse.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 24,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
    ),
    ClassAbilityDef(
      id: AbilityId.lifebloom,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Lifebloom',
      shortLabel: 'Bloom',
      description: 'HoT bloom on the lowest ally.',
      unlockLevel: 9,
      cooldown: 9,
      resourceCost: 16,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70E090,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.nourish,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Nourish',
      shortLabel: 'Nour',
      description: 'Efficient big heal.',
      unlockLevel: 11,
      cooldown: 6,
      resourceCost: 20,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
    ),
    ClassAbilityDef(
      id: AbilityId.tranquility,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Tranquility',
      shortLabel: 'Calm',
      description: 'Signature party mend.',
      unlockLevel: 11,
      cooldown: 45,
      resourceCost: 35,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.signature,
      coeff: 2.1,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF90E090,
        groundDisc: true,
        groundLife: 5.5,
        groundArgb: 0x6690E090,
        groundRadius: 3.2,
      ),
    ),
    // AbilityId.barkskinResto — legacy save key; player-facing name is Nature's Swiftness.
    ClassAbilityDef(
      id: AbilityId.barkskinResto,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationDruid,
      name: 'Nature\'s Swiftness',
      shortLabel: 'Swift',
      description: 'Emergency big heal.',
      unlockLevel: 12,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyHeal,
      tier: AbilityCastTier.emergency,
      coeff: 2.2,
    ),
];
