// Hunter kits (Beast Mastery / Marksmanship / Survival)
part of '../class_ability.dart';

const List<ClassAbilityDef> _hunterKit = <ClassAbilityDef>[
    // —— beastMastery ——
    ClassAbilityDef(
      id: AbilityId.aspectOfHawk,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Aspect of the Hawk',
      shortLabel: 'Hawk',
      description: 'Always on: ranged power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.18,
    ),
    ClassAbilityDef(
      id: AbilityId.arcaneShot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Arcane Shot',
      shortLabel: 'ArcShot',
      description: 'Quick ranged bolt.',
      unlockLevel: 3,
      cooldown: 4,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.08,
    ),
    ClassAbilityDef(
      id: AbilityId.killCommand,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Kill Command',
      shortLabel: 'Kill',
      description: 'Pet-style heavy hit.',
      unlockLevel: 5,
      cooldown: 5.5,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.48,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8C060,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.multiShot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Multi-Shot',
      shortLabel: 'Multi',
      description: 'AoE around focus.',
      unlockLevel: 7,
      cooldown: 6,
      resourceCost: 14,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8D080,
      ),

      aoeShape: AbilityAoeShape.fan,
    ),
    ClassAbilityDef(
      id: AbilityId.bestialWrath,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Bestial Wrath',
      shortLabel: 'BeastW',
      description: 'Self haste buff.',
      unlockLevel: 9,
      cooldown: 30,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.intimidation,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Intimidation',
      shortLabel: 'Intim',
      description: 'Root nearest foe.',
      unlockLevel: 11,
      cooldown: 16,
      resourceCost: 15,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.beastWithin,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'The Beast Within',
      shortLabel: 'Beast',
      description: 'Signature damage window.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFFFB060,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.feignDeath,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.beastMastery,
      name: 'Feign Death',
      shortLabel: 'Feign',
      description: 'Emergency drop aggro.',
      unlockLevel: 12,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— marksmanship ——
    ClassAbilityDef(
      id: AbilityId.trueshotAura,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Trueshot Aura',
      shortLabel: 'TAura',
      description: 'Always on: crit lean.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.22,
      passiveHasteMul: 1.06,
    ),
    ClassAbilityDef(
      id: AbilityId.steadyShot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Steady Shot',
      shortLabel: 'Steady',
      description: 'Reliable ranged shot.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.05,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8D080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.aimedShot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Aimed Shot',
      shortLabel: 'Aimed',
      description: 'Heavy carefully aimed bolt.',
      unlockLevel: 5,
      cooldown: 6.5,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.72,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8D080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.chimeraShot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Chimera Shot',
      shortLabel: 'Chim',
      description: 'Nature + frost hybrid hit.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.35,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D070,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.volley,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Volley',
      shortLabel: 'Volley',
      description: 'Arrow rain on the pack.',
      unlockLevel: 9,
      cooldown: 9,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.78,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8D080,
        groundDisc: true,
        groundLife: 2.8,
        groundArgb: 0x66E8D080,
      ),

      aoeShape: AbilityAoeShape.rain,
    ),
    ClassAbilityDef(
      id: AbilityId.multiShotMm,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Multi-Shot',
      shortLabel: 'Multi',
      description: 'Fan arrows into the pack around your focus.',
      unlockLevel: 8,
      cooldown: 8,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.88,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFE8D080,
      ),
      aoeShape: AbilityAoeShape.fan,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.rapidFire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Rapid Fire',
      shortLabel: 'Rapid',
      description: 'Self haste window.',
      unlockLevel: 11,
      cooldown: 32,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.trueshot,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Trueshot',
      shortLabel: 'TShot',
      description: 'Signature ranged amplify.',
      unlockLevel: 11,
      cooldown: 45,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFFFE080,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.deterrence,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.marksmanship,
      name: 'Deterrence',
      shortLabel: 'Deter',
      description: 'Emergency self shield.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— survival ——
    ClassAbilityDef(
      id: AbilityId.trapMastery,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Trap Mastery',
      shortLabel: 'TrapM',
      description: 'Always on: stronger roots.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.26,
      passiveRootBonus: 1.0,
    ),
    ClassAbilityDef(
      id: AbilityId.explosiveShot,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Explosive Shot',
      shortLabel: 'Expl',
      description: 'Burst fire shot.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF9040),
    ),
    ClassAbilityDef(
      id: AbilityId.serpentSting,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Serpent Sting',
      shortLabel: 'Sting',
      description: 'Poisoned ranged hit.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.85,
      boltStyle: SpellBoltStyle.poison,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.poison,
        castArgb: 0xFF70D050,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.explosiveTrap,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Explosive Trap',
      shortLabel: 'ETrap',
      description: 'AoE around self.',
      unlockLevel: 7,
      cooldown: 12,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.48,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF8050,
        groundDisc: true,
        groundLife: 3.0,
        groundArgb: 0x88FF7040,
        groundRadius: 2.6,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.freezingTrap,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Freezing Trap',
      shortLabel: 'Freeze',
      description: 'Root nearest foe.',
      unlockLevel: 9,
      cooldown: 16,
      resourceCost: 15,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90D8FF,
        groundDisc: true,
        groundLife: 2.0,
        groundArgb: 0x6690D0FF,
        groundRadius: 1.8,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.mongooseBite,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Mongoose Bite',
      shortLabel: 'MBite',
      description: 'Melee-range snap.',
      unlockLevel: 11,
      cooldown: 5,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.3,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFE8C090,
      ),

      gate: AbilityGate(maxRange: 1.85),
    ),
    ClassAbilityDef(
      id: AbilityId.multiShotSurv,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Multi-Shot',
      shortLabel: 'Multi',
      description: 'Fan bolts into the pack around your focus.',
      unlockLevel: 8,
      cooldown: 6,
      resourceCost: 12,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.50,
      boltStyle: SpellBoltStyle.arrow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arrow,
        castArgb: 0xFFC0D080,
      ),

      aoeShape: AbilityAoeShape.fan,
    ),
    ClassAbilityDef(
      id: AbilityId.blackArrow,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Black Arrow',
      shortLabel: 'BArrow',
      description: 'Signature dark bolt.',
      unlockLevel: 11,
      cooldown: 14,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.4,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF9060C0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.disengage,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.survival,
      name: 'Disengage',
      shortLabel: 'LeapOut',
      description: 'Emergency kite buff.',
      unlockLevel: 12,
      cooldown: 25,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
