// Mage kits (Fire / Arcane / Frost)
part of '../class_ability.dart';

const List<ClassAbilityDef> _mageKit = <ClassAbilityDef>[
    // —— Mage (Fire) ——
    ClassAbilityDef(
      id: AbilityId.arcaneIntellect,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Arcane Intellect',
      shortLabel: 'Intellect',
      description: 'Always on: personal spell power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: false,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.24,
    ),
    ClassAbilityDef(
      id: AbilityId.fireball,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Fireball',
      shortLabel: 'Ball',
      description: 'Hurls a heavy fire bolt at your focus.',
      unlockLevel: 3,
      cooldown: 5.8,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.95,
      castDelaySeconds: 1.8,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF6030,
      ),

      customId: AbilityCustomId.fireball,
      gate: AbilityGate(
        requireFocus: true,
        maxRangePad: 0.5,
        hotStreakBlocks: true,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.livingBomb,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Living Bomb',
      shortLabel: 'LBomb',
      description: 'DoT that explodes for splash damage.',
      unlockLevel: 5,
      cooldown: 8,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.65,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF5020,
      ),

      customId: AbilityCustomId.livingBomb,
      fireMode: AbilityFireMode.dotTick,
      gate: AbilityGate(requireFocus: true, livingBombRefresh: true),
    ),
    ClassAbilityDef(
      id: AbilityId.frostNova,
      boltStyle: SpellBoltStyle.frost,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Frost Nova',
      shortLabel: 'FNova',
      description: 'Freeze nearby enemies in place briefly.',
      unlockLevel: 7,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.frostNova,
      gate: AbilityGate(peelRange: 1.6, peelScanRange: 2.4),
    ),
    ClassAbilityDef(
      id: AbilityId.blastWave,
      boltStyle: SpellBoltStyle.fire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Blast Wave',
      shortLabel: 'Blast',
      description: 'Fire AoE knock — burns packs around you.',
      unlockLevel: 9,
      cooldown: 8,
      resourceCost: 25,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.85,

      customId: AbilityCustomId.blastWave,
      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.flamestrike,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Flamestrike',
      shortLabel: 'FStrike',
      description: 'Ground fire on the pack around you.',
      unlockLevel: 8,
      cooldown: 10,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 1.28,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF6030,
        groundDisc: true,
        groundLife: 3.2,
        groundArgb: 0x66FF5020,
        groundRadius: 2.8,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.blink,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Blink',
      shortLabel: 'Blink',
      description: 'Teleport toward preferred casting range.',
      unlockLevel: 10,
      cooldown: 12,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.blink,
      gate: AbilityGate(requireFocus: true, maxRangeMul: 0.55),
    ),
    ClassAbilityDef(
      id: AbilityId.combustion,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Combustion',
      shortLabel: 'Combust',
      description: 'Short window of massive spell damage.',
      unlockLevel: 11,
      cooldown: 55,
      resourceCost: 30,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF6020),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 4,
      gate: AbilityGate(requireFocus: true, holdLongCdOnTrash: false),
    ),
    ClassAbilityDef(
      id: AbilityId.pyroblast,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Pyroblast',
      shortLabel: 'Pyro',
      description: 'Free Pyroblast after two Fireball crits (Hot Streak).',
      unlockLevel: 11,
      cooldown: 15,
      resourceCost: 28,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.45,
      castDelaySeconds: 2.4,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF4010),

      customId: AbilityCustomId.pyroblast,
      gate: AbilityGate(
        requireFocus: true,
        maxRangePad: 0.5,
        hotStreakOnly: true,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.iceBlock,
      boltStyle: SpellBoltStyle.frost,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.fire,
      name: 'Ice Block',
      shortLabel: 'Ice',
      description: 'Emergency immunity bubble when near death.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.iceBlock,
      gate: AbilityGate(casterHpMax: 0.28),
    ),

    // —— arcane ——
    ClassAbilityDef(
      id: AbilityId.arcanePowerPassive,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Arcane Brilliance',
      shortLabel: 'Brill',
      description: 'Always on: mana lean.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.12,
    ),
    ClassAbilityDef(
      id: AbilityId.arcaneBlast,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Arcane Blast',
      shortLabel: 'ABlast',
      description: 'Stacking arcane bolt.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.2,
      castDelaySeconds: 1.4,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFC070FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.arcaneMissiles,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Arcane Missiles',
      shortLabel: 'Missiles',
      description: 'Barrage damage.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.3,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFC070FF,
      ),

      gate: AbilityGate(arcaneChargesMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.arcaneExplosion,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Arcane Explosion',
      shortLabel: 'AE',
      description: 'Arcane burst on the pack around your focus.',
      unlockLevel: 7,
      cooldown: 5,
      resourceCost: 12,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFC070FF,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x88C070FF,
        groundRadius: 3.5,
      ),

      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.slow,
      boltStyle: SpellBoltStyle.arcane,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Slow',
      shortLabel: 'Slow',
      description: 'Slow nearest foe attack speed.',
      unlockLevel: 9,
      cooldown: 14,
      resourceCost: 12,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.presenceOfMind,
      boltStyle: SpellBoltStyle.arcane,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Presence of Mind',
      shortLabel: 'PMind',
      description: 'Self haste buff.',
      unlockLevel: 11,
      cooldown: 30,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.arcanePower,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Arcane Power',
      shortLabel: 'ArcPwr',
      description: 'Signature damage amp for Arcane spells.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 25,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.arcane,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.arcane,
        castArgb: 0xFFC070FF,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 7,
    ),
    ClassAbilityDef(
      id: AbilityId.arcaneIceBlock,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.arcane,
      name: 'Ice Block',
      shortLabel: 'IceBlk',
      description: 'Emergency immunity.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.iceBlock,
    ),

    // —— frostMage ——
    ClassAbilityDef(
      id: AbilityId.frostArmor,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Frost Armor',
      shortLabel: 'FArmor',
      description: 'Always on: chill defense.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveInMul: 0.92,
      passiveOutMul: 1.12,
      passiveRootBonus: 0.5,
    ),
    ClassAbilityDef(
      id: AbilityId.frostbolt,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Frostbolt',
      shortLabel: 'FBolt',
      description: 'Chilling bolt.',
      unlockLevel: 3,
      cooldown: 3.5,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      castDelaySeconds: 1.5,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF80D0FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.iceLance,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Ice Lance',
      shortLabel: 'Lance',
      description: 'Shatter-style hit.',
      unlockLevel: 5,
      cooldown: 4,
      resourceCost: 10,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90E8FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.coneOfCold,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Cone of Cold',
      shortLabel: 'Cone',
      description: 'Frost cone on the pack around your focus.',
      unlockLevel: 7,
      cooldown: 6,
      resourceCost: 12,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 1.20,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90E8FF,
        groundDisc: true,
        groundLife: 1.2,
        groundArgb: 0x6690D8FF,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.blizzard,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Blizzard',
      shortLabel: 'Blizz',
      description: 'Frost rain on the pack around your focus.',
      unlockLevel: 8,
      cooldown: 8,
      resourceCost: 16,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.90,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90D8FF,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x6690C8FF,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.frostNovaMage,
      boltStyle: SpellBoltStyle.frost,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Frost Nova',
      shortLabel: 'FrNova',
      description: 'Root nearby foes.',
      unlockLevel: 9,
      cooldown: 12,
      resourceCost: 18,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,

      gate: AbilityGate(peelRange: 1.6, peelScanRange: 2.5),
    ),
    ClassAbilityDef(
      id: AbilityId.icyVeins,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Icy Veins',
      shortLabel: 'Veins',
      description: 'Self haste buff.',
      unlockLevel: 11,
      cooldown: 35,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.summonWaterElemental,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Water Elemental',
      shortLabel: 'WElem',
      description: 'Summon a Water Elemental ally for 28s.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.frost,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.frost,
        castArgb: 0xFF90D8FF,
      ),
      summonCount: 1,
      summonDuration: 28,
      summonAtkScale: 0.40,
      summonName: 'Water Elemental',
      summonIdPrefix: 'water',
    ),
    ClassAbilityDef(
      id: AbilityId.frostMageIceBlock,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.frostMage,
      name: 'Ice Block',
      shortLabel: 'IceBlk',
      description: 'Emergency immunity.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.iceBlock,
    ),
];
