// Paladin kits (Holy / Protection / Retribution)
part of '../class_ability.dart';

const List<ClassAbilityDef> _paladinKit = <ClassAbilityDef>[
    // —— holyPaladin ——
    ClassAbilityDef(
      id: AbilityId.holyLightAura,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Devotion',
      shortLabel: 'DAura',
      description: 'Always on: stronger heals.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: false,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveHealMul: 1.32,
    ),
    ClassAbilityDef(
      id: AbilityId.holyShock,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Holy Shock',
      shortLabel: 'HShock',
      description: 'Instant heal if an ally is hurt; otherwise holy damage.',
      unlockLevel: 3,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.3,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.flashOfLight,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Flash of Light',
      shortLabel: 'FoL',
      description: 'Fast heal on lowest ally.',
      unlockLevel: 5,
      cooldown: 4.5,
      resourceCost: 16,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.sacredShield,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Sacred Shield',
      shortLabel: 'SaShld',
      description: 'Absorb on lowest ally.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 20,
      effect: AbilityEffectKind.absorb,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
    ),
    ClassAbilityDef(
      id: AbilityId.holyLight,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Holy Light',
      shortLabel: 'HLight',
      description: 'Big heal on injured ally.',
      unlockLevel: 9,
      cooldown: 7,
      resourceCost: 28,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.7,
      castDelaySeconds: 1.8,
    ),
    ClassAbilityDef(
      id: AbilityId.beaconOfLight,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Beacon (tank)',
      shortLabel: 'Beacon',
      description: 'Mark an ally — your heals peel onto them.',
      unlockLevel: 11,
      cooldown: 12,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      gate: AbilityGate(skipIfBeaconAbove: 10),
    ),
    ClassAbilityDef(
      id: AbilityId.consecrationHoly,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Consecration',
      shortLabel: 'Cons',
      description: 'Holy ground pulse — clears the pack underfoot.',
      unlockLevel: 7,
      cooldown: 10,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.28,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFF0A8,
        groundDisc: true,
        groundLife: 5.0,
        groundArgb: 0x66FFE8A0,
        groundRadius: 2.7,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.divineFavor,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Divine Favor',
      shortLabel: 'Favor',
      description: 'Heal window — your next heals hit harder.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFF0A8),

      selfBuffKind: AbilitySelfBuffKind.healAmp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.layOnHands,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPaladin,
      name: 'Lay on Hands',
      shortLabel: 'LoH',
      description: 'Emergency big heal on lowest ally.',
      unlockLevel: 12,
      cooldown: 60,
      effect: AbilityEffectKind.emergencyHeal,
      tier: AbilityCastTier.emergency,
      coeff: 3.2,
    ),

    // —— protPaladin ——
    ClassAbilityDef(
      id: AbilityId.righteousFury,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Righteous Fury',
      shortLabel: 'RFury',
      description: 'Always on: stronger aggro.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 0.97,
      passiveInMul: 0.82,
    ),
    ClassAbilityDef(
      id: AbilityId.avengersShield,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Avenger\'s Shield',
      shortLabel: 'Avenge',
      description: 'Ranged bash on nearest foe. Requires shield.',
      unlockLevel: 3,
      cooldown: 8,
      resourceCost: 18,
      requiresShield: true,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.holyShield,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Holy Shield',
      shortLabel: 'HolySh',
      description: 'Holy charges on your shield — block more while you tank. Requires shield.',
      unlockLevel: 5,
      cooldown: 10,
      resourceCost: 15,
      requiresShield: true,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.block,
      selfBuffDuration: 6,
    ),
    ClassAbilityDef(
      id: AbilityId.hammerOfTheRighteous,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Hammer of the Righteous',
      shortLabel: 'Hammer',
      description: 'AoE holy smash.',
      unlockLevel: 7,
      cooldown: 6,
      resourceCost: 12,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.7,

      aoeShape: AbilityAoeShape.nova,
    ),
    ClassAbilityDef(
      id: AbilityId.consecration,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Consecration',
      shortLabel: 'Cons',
      description: 'Ground AoE burn.',
      unlockLevel: 9,
      cooldown: 9,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.32,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
        groundDisc: true,
        groundLife: 6.0,
        groundArgb: 0x66FFE080,
        groundRadius: 2.7,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.shieldOfRighteousness,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Shield of Righteousness',
      shortLabel: 'SoR',
      description: 'Heavy shield strike. Requires shield.',
      unlockLevel: 11,
      cooldown: 5.5,
      resourceCost: 20,
      requiresShield: true,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
    ),
    ClassAbilityDef(
      id: AbilityId.holyWrath,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Holy Wrath',
      shortLabel: 'HWrath',
      description: 'Signature stun AoE.',
      unlockLevel: 11,
      cooldown: 22,
      resourceCost: 25,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 0.95,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
        groundDisc: true,
        groundLife: 2.2,
        groundArgb: 0x88FFE8A0,
        groundRadius: 2.6,
      ),

      aoeShape: AbilityAoeShape.nova,
    ),
    ClassAbilityDef(
      id: AbilityId.divineProtection,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Divine Protection',
      shortLabel: 'DProt',
      description: 'Emergency DR bubble.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.handOfReckoning,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protPaladin,
      name: 'Hand of Reckoning',
      shortLabel: 'Reckon',
      description: 'Hard taunt nearest loose foe.',
      unlockLevel: 4,
      cooldown: 8,
      resourceCost: 10,
      effect: AbilityEffectKind.taunt,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFE8A0),
    ),

    // —— retribution ——
    ClassAbilityDef(
      id: AbilityId.sealOfCommand,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Seal of Command',
      shortLabel: 'Seal',
      description: 'Always on: bonus strike power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 2.05,
    ),
    ClassAbilityDef(
      id: AbilityId.crusaderStrike,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Crusader Strike',
      shortLabel: 'Crus',
      description: 'Core melee holy strike.',
      unlockLevel: 3,
      cooldown: 4,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.78,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.judgment,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Judgment',
      shortLabel: 'Judge',
      description: 'Ranged holy verdict.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.58,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.divineStorm,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Divine Storm',
      shortLabel: 'DStorm',
      description: 'AoE holy whirl.',
      unlockLevel: 7,
      cooldown: 9,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.50,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
        groundDisc: true,
        groundLife: 3.2,
        groundArgb: 0x88FFE080,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.hammerOfWrath,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Hammer of Wrath',
      shortLabel: 'HoWrath',
      description: 'Execute-style holy hammer.',
      unlockLevel: 9,
      cooldown: 7,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.75,

      gate: AbilityGate(executeHpFrac: 0.25),
    ),
    ClassAbilityDef(
      id: AbilityId.zealotry,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Zealotry',
      shortLabel: 'Zealot',
      description: 'Holy damage window — hit harder.',
      unlockLevel: 11,
      cooldown: 35,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.templarsVerdict,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Templar\'s Verdict',
      shortLabel: 'Verdict',
      description: 'Signature heavy finisher.',
      unlockLevel: 11,
      cooldown: 8,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 2.85,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFF0C0),
    ),
    ClassAbilityDef(
      id: AbilityId.divineShield,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.retribution,
      name: 'Divine Shield',
      shortLabel: 'Invuln',
      description: 'Emergency immunity.',
      unlockLevel: 12,
      cooldown: 60,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
