// Priest kits (Discipline / Holy / Shadow)
part of '../class_ability.dart';

const List<ClassAbilityDef> _priestKit = <ClassAbilityDef>[
    // —— Disc Priest ——
    ClassAbilityDef(
      id: AbilityId.innerFire,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Inner Fire',
      shortLabel: 'Inner',
      description: 'Always on: tougher shields and stronger heals.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: false,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      innerFire: true,
      passiveHealMul: 1.36,
      passiveInMul: 0.94,
    ),
    ClassAbilityDef(
      id: AbilityId.powerWordShield,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Power Word: Shield',
      shortLabel: 'PWS',
      description: 'Absorb shield on the lowest-health ally.',
      unlockLevel: 3,
      cooldown: 6.5,
      resourceCost: 18,
      effect: AbilityEffectKind.absorb,
      tier: AbilityCastTier.filler,
      coeff: 2.0,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFE8D090,
        groundDisc: true,
        groundLife: 2.2,
        groundArgb: 0x66FFE8A0,
        groundRadius: 1.6,
      ),

      customId: AbilityCustomId.powerWordShield,
    ),
    ClassAbilityDef(
      id: AbilityId.prayerOfMending,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Prayer of Mending',
      shortLabel: 'Mend',
      description: 'Bounce heal that triggers when an ally is hit.',
      unlockLevel: 5,
      cooldown: 9,
      resourceCost: 18,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.0,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFF0C0),

      customId: AbilityCustomId.prayerOfMending,
      fireMode: AbilityFireMode.onHitBounce,
      gate: AbilityGate(needsPomTarget: true),
    ),
    ClassAbilityDef(
      id: AbilityId.penance,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Penance',
      shortLabel: 'Penance',
      description: 'Channel holy bolts — tops injured allies or burns foes.',
      unlockLevel: 7,
      cooldown: 7.5,
      resourceCost: 24,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.signature,
      coeff: 0.62,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFE8A0),

      customId: AbilityCustomId.penance,
      gate: AbilityGate(needsPenance: true),
    ),
    ClassAbilityDef(
      id: AbilityId.powerWordFortitude,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Power Word: Fortitude',
      shortLabel: 'Fort',
      description: 'Party stamina buff — more max HP for a while.',
      unlockLevel: 9,
      cooldown: 30,
      resourceCost: 25,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.powerWordFortitude,
      gate: AbilityGate(fortitudeRefresh: true),
    ),
    ClassAbilityDef(
      id: AbilityId.flashHeal,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Flash Heal',
      shortLabel: 'DFlash',
      description: 'Direct heal on the most injured ally.',
      unlockLevel: 11,
      cooldown: 4.5,
      resourceCost: 20,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFF0B0),
    ),
    ClassAbilityDef(
      id: AbilityId.painSuppression,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Pain Suppression',
      shortLabel: 'Pain',
      description: 'Emergency damage reduction on a critically low ally.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 10,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFE0C070,
        groundDisc: true,
        groundLife: 2.5,
        groundArgb: 0x66E0C070,
        groundRadius: 1.5,
      ),

      customId: AbilityCustomId.painSuppression,
      gate: AbilityGate(needsPainTarget: true),
    ),
    ClassAbilityDef(
      id: AbilityId.powerInfusion,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.discipline,
      name: 'Power Infusion',
      shortLabel: 'Infusion',
      description: 'Haste buff on your strongest damage dealer.',
      unlockLevel: 12,
      cooldown: 55,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFD070),

      customId: AbilityCustomId.powerInfusion,
      gate: AbilityGate(
        requireFocus: true,
        needsPiTarget: true,
        holdLongCdOnTrash: false,
      ),
    ),

    // —— holyPriest ——
    ClassAbilityDef(
      id: AbilityId.spiritOfRedemption,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Spirit of Redemption',
      shortLabel: 'Redeem',
      description: 'Always on: stronger heals.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveHealMul: 1.32,
    ),
    ClassAbilityDef(
      id: AbilityId.renew,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Renew',
      shortLabel: 'Renew',
      description: 'HoT-style heal pulse.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.35,
    ),
    ClassAbilityDef(
      id: AbilityId.holyPriestFlash,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Flash Heal',
      shortLabel: 'HFlash',
      description: 'Quick emergency heal.',
      unlockLevel: 5,
      cooldown: 4,
      resourceCost: 18,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.holy, castArgb: 0xFFFFE8A0),
    ),
    ClassAbilityDef(
      id: AbilityId.circleOfHealing,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Circle of Healing',
      shortLabel: 'CoH',
      description: 'Heal lowest, splash ally.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 24,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.4,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFF0C0,
        groundDisc: true,
        groundLife: 2.2,
        groundArgb: 0x66FFE8A0,
        groundRadius: 2.4,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.guardianSpirit,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Guardian Spirit',
      shortLabel: 'GS',
      description: 'Emergency guardian save on the lowest ally.',
      unlockLevel: 9,
      cooldown: 45,
      resourceCost: 10,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
      coeff: 1.6,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFD090,
        groundDisc: true,
        groundLife: 2.8,
        groundArgb: 0x77FFE090,
        groundRadius: 1.7,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.holyPriestNova,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Holy Nova',
      shortLabel: 'HNova',
      description: 'Party heal pulse around you.',
      unlockLevel: 11,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 0.85,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFF8D0,
        groundDisc: true,
        groundLife: 2.0,
        groundArgb: 0x66FFF0B0,
        groundRadius: 2.8,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.divineHymn,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Divine Hymn',
      shortLabel: 'Hymn',
      description: 'Signature party heal.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 30,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.signature,
      coeff: 1.6,
      boltStyle: SpellBoltStyle.holy,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.holy,
        castArgb: 0xFFFFE080,
        groundDisc: true,
        groundLife: 3.5,
        groundArgb: 0x88FFE8A0,
        groundRadius: 3.0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.desperatePrayer,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.holyPriest,
      name: 'Desperate Prayer',
      shortLabel: 'DPray',
      description: 'Emergency self heal.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyHeal,
      tier: AbilityCastTier.emergency,
      coeff: 2.4,
    ),

    // —— shadow ——
    ClassAbilityDef(
      id: AbilityId.shadowform,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Shadowform',
      shortLabel: 'ShForm',
      description: 'Always on: shadow power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.16,
      passiveInMul: 1.04,
    ),
    ClassAbilityDef(
      id: AbilityId.mindFlay,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Mind Flay',
      shortLabel: 'Flay',
      description: 'Channeled shadow damage.',
      unlockLevel: 3,
      cooldown: 4,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.05,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.vampiricTouch,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Vampiric Touch',
      shortLabel: 'VTouch',
      description: 'Shadow strike that refunds mana.',
      unlockLevel: 5,
      cooldown: 7,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.devouringPlague,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Devouring Plague',
      shortLabel: 'Plague',
      description: 'Heavy shadow strike.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.35,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.shadowWordPain,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Shadow Word: Pain',
      shortLabel: 'SWPain',
      description: 'DoT-style bolt.',
      unlockLevel: 9,
      cooldown: 6,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.85,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.mindSear,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Mind Sear',
      shortLabel: 'Sear',
      description: 'Channel shadow damage into the pack.',
      unlockLevel: 9,
      cooldown: 9,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.76,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
        groundDisc: true,
        groundLife: 2.2,
        groundArgb: 0x669040C0,
        groundRadius: 2.9,
      ),

      aoeShape: AbilityAoeShape.rain,
    ),
    ClassAbilityDef(
      id: AbilityId.psychicScream,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Psychic Scream',
      shortLabel: 'Fear',
      description: 'Root nearby foes.',
      unlockLevel: 11,
      cooldown: 18,
      resourceCost: 15,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.mindBlast,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Mind Blast',
      shortLabel: 'MBlast',
      description: 'Signature shadow nuke.',
      unlockLevel: 11,
      cooldown: 7,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.75,
      castDelaySeconds: 1.5,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.dispersion,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.shadow,
      name: 'Dispersion',
      shortLabel: 'Fade',
      description: 'Emergency DR / mana.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
