// Rogue kits (Combat / Assassination / Subtlety)
part of '../class_ability.dart';

const List<ClassAbilityDef> _rogueKit = <ClassAbilityDef>[
    // —— Rogue (Combat) ——
    ClassAbilityDef(
      id: AbilityId.sinisterStrike,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Sinister Strike',
      shortLabel: 'SinStr',
      description: 'Build combo points on every swing.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,

      fireMode: AbilityFireMode.passive,
      passiveOutMul: 1.62,
    ),
    ClassAbilityDef(
      id: AbilityId.sliceAndDice,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Slice and Dice',
      shortLabel: 'Slice',
      description: 'Spend combo for attack-speed buff.',
      unlockLevel: 3,
      cooldown: 1,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.sliceAndDice,
      gate: AbilityGate(comboMin: 2, sliceAndDiceRefresh: true),
    ),
    ClassAbilityDef(
      id: AbilityId.eviscerate,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Eviscerate',
      shortLabel: 'Evis',
      description: 'Finisher — damage scales with combo points.',
      unlockLevel: 5,
      cooldown: 1.2,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.18,

      fireMode: AbilityFireMode.swingRider,
      showInHud: true,
    ),
    ClassAbilityDef(
      id: AbilityId.kidneyShot,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Kidney Shot',
      shortLabel: 'Kidney',
      description: 'Stun the focus target briefly.',
      unlockLevel: 7,
      cooldown: 14,
      resourceCost: 25,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.kidneyShot,
      gate: AbilityGate(
        requireFocus: true,
        comboMin: 5,
        sliceAndDiceMin: 2,
        focusRootMax: 0.5,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.bladeFlurry,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Blade Flurry',
      shortLabel: 'Blades',
      description: 'Your attacks also hit one extra nearby foe.',
      unlockLevel: 9,
      cooldown: 24,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,
      coeff: 0.85,

      customId: AbilityCustomId.bladeFlurry,
      selfBuffKind: AbilitySelfBuffKind.cleave,
      selfBuffDuration: 4,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.sprint,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Sprint',
      shortLabel: 'Sprint',
      description: 'Burst of move speed to close or kite.',
      unlockLevel: 11,
      cooldown: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.sprint,
      gate: AbilityGate(nearPackLeader: true, minRangeMul: 1.85),
    ),
    ClassAbilityDef(
      id: AbilityId.vanish,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Vanish',
      shortLabel: 'Vanish',
      description: 'Drop aggro and reset when low.',
      unlockLevel: 11,
      cooldown: 40,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.vanish,
      gate: AbilityGate(casterHpMax: 0.3),
    ),
    ClassAbilityDef(
      id: AbilityId.killingSpree,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Killing Spree',
      shortLabel: 'Spree',
      description: 'Dash between foes with a flurry of strikes.',
      unlockLevel: 12,
      cooldown: 55,
      resourceCost: 0,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 0.95,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFD080,
        groundDisc: true,
        groundLife: 2.0,
        groundArgb: 0x88FFE08A,
        groundRadius: 2.2,
      ),

      customId: AbilityCustomId.killingSpree,
      aoeShape: AbilityAoeShape.nova,
      gate: AbilityGate(anyCombatWindow: true, packMin: 2, executeHpFrac: 0.35),
    ),
    ClassAbilityDef(
      id: AbilityId.fanOfKnivesCombat,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.combat,
      name: 'Fan of Knives',
      shortLabel: 'CFoK',
      description: 'Knives into a big pack — not used on two-target cleave.',
      unlockLevel: 10,
      cooldown: 9,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.16,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFD8C070,
        groundDisc: true,
        groundLife: 1.4,
        groundArgb: 0x66C0A050,
        groundRadius: 2.6,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 4),
    ),

    // —— assassination ——
    ClassAbilityDef(
      id: AbilityId.improvedPoisons,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Improved Poisons',
      shortLabel: 'Poison',
      description: 'Always on: toxin damage.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.28,
    ),
    ClassAbilityDef(
      id: AbilityId.mutilate,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Mutilate',
      shortLabel: 'Mutil',
      description: 'Twin dagger strike.',
      unlockLevel: 3,
      cooldown: 4,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.45,
    ),
    ClassAbilityDef(
      id: AbilityId.envenom,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Envenom',
      shortLabel: 'Enven',
      description: 'Poison finisher.',
      unlockLevel: 5,
      cooldown: 5,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.poison,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.poison,
        castArgb: 0xFF90D040,
      ),

      gate: AbilityGate(comboMin: 3),
    ),
    ClassAbilityDef(
      id: AbilityId.garrote,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Garrote',
      shortLabel: 'Garrote',
      description: 'Silence-style bleed hit.',
      unlockLevel: 7,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.9,
      boltStyle: SpellBoltStyle.poison,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.poison,
        castArgb: 0xFF70B020,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.rupture,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Rupture',
      shortLabel: 'Rupture',
      description: 'DoT-style strike.',
      unlockLevel: 9,
      cooldown: 8,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.0,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.coldBlood,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Cold Blood',
      shortLabel: 'Cold',
      description: 'Self crit amp window for poisons and finishers.',
      unlockLevel: 11,
      cooldown: 35,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 6,
    ),
    ClassAbilityDef(
      id: AbilityId.fanOfKnives,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Fan of Knives',
      shortLabel: 'AFoK',
      description: 'Throw knives at every foe nearby.',
      unlockLevel: 9,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.95,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFC0D070,
        groundDisc: true,
        groundLife: 1.4,
        groundArgb: 0x66A0C050,
        groundRadius: 2.6,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.vendetta,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Vendetta',
      shortLabel: 'Vend',
      description: 'Signature damage amp on your attacks.',
      unlockLevel: 11,
      cooldown: 45,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFFF4040,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.cloakOfShadows,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.assassination,
      name: 'Cloak of Shadows',
      shortLabel: 'Cloak',
      description: 'Emergency cleanse DR.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— subtlety ——
    ClassAbilityDef(
      id: AbilityId.masterOfSubtlety,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Master of Subtlety',
      shortLabel: 'Subtle',
      description: 'Always on: opener power + haste.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.46,
      passiveHasteMul: 1.08,
    ),
    ClassAbilityDef(
      id: AbilityId.hemorrhage,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Hemorrhage',
      shortLabel: 'Hemo',
      description: 'Bleed strike.',
      unlockLevel: 3,
      cooldown: 3.5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.28,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB090E0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.backstab,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Backstab',
      shortLabel: 'Stab',
      description: 'Heavy positional strike.',
      unlockLevel: 5,
      cooldown: 5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.60,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF9070C8,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.shadowstep,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Shadowstep',
      shortLabel: 'SStep',
      description: 'Close gap / haste burst.',
      unlockLevel: 7,
      cooldown: 14,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8060C0,
        groundDisc: true,
        groundLife: 1.4,
        groundArgb: 0x668060C0,
        groundRadius: 1.4,
      ),

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.premeditation,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Premeditation',
      shortLabel: 'PreMed',
      description: 'Grant combo resource.',
      unlockLevel: 9,
      cooldown: 12,
      effect: AbilityEffectKind.grantResource,
      tier: AbilityCastTier.filler,
      coeff: 25,
    ),
    ClassAbilityDef(
      id: AbilityId.shadowDance,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Shadow Dance',
      shortLabel: 'SDance',
      description: 'Vanish into shadow — haste openers.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFC090E8,
        groundDisc: true,
        groundLife: 3.0,
        groundArgb: 0x77A070E0,
        groundRadius: 2.2,
      ),

      customId: AbilityCustomId.shadowDance,
    ),
    ClassAbilityDef(
      id: AbilityId.fanOfKnivesSub,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Fan of Knives',
      shortLabel: 'SFoK',
      description: 'Shadow knives into the pack.',
      unlockLevel: 9,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.95,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB090E0,
        groundDisc: true,
        groundLife: 1.4,
        groundArgb: 0x668060C0,
        groundRadius: 2.6,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.eviscerateSub,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Eviscerate',
      shortLabel: 'Evis',
      description: 'Combo finisher dump.',
      unlockLevel: 7,
      cooldown: 1.2,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.65,
      showInHud: true,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFD0A0FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.cheapShot,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Cheap Shot',
      shortLabel: 'Cheap',
      description: 'Stun nearest foe.',
      unlockLevel: 11,
      cooldown: 14,
      resourceCost: 20,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.preparation,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.subtlety,
      name: 'Preparation',
      shortLabel: 'Reset',
      description: 'Emergency: reset your other combat cooldowns.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
