// Shaman kits (Elemental / Enhancement / Restoration)
part of '../class_ability.dart';

const List<ClassAbilityDef> _shamanKit = <ClassAbilityDef>[
    // —— elemental ——
    ClassAbilityDef(
      id: AbilityId.elementalFocus,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Elemental Focus',
      shortLabel: 'EFocus',
      description: 'Always on: spell power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.14,
      passiveHasteMul: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.lightningBolt,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Lightning Bolt',
      shortLabel: 'LBolt',
      description: 'Core nature bolt.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
    ),
    ClassAbilityDef(
      id: AbilityId.flameShock,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Flame Shock',
      shortLabel: 'Flame',
      description: 'Maintain a fire DoT on your focus.',
      unlockLevel: 4,
      cooldown: 6,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.72,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF8040),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.lavaBurst,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Lava Burst',
      shortLabel: 'Lava',
      description: 'Heavy fire nuke.',
      unlockLevel: 5,
      cooldown: 7,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF6020,
      ),
      castDelaySeconds: 0.45,
    ),
    ClassAbilityDef(
      id: AbilityId.chainLightning,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Chain Lightning',
      shortLabel: 'Chain',
      description: 'AoE lightning hops.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 24,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.72,
      boltStyle: SpellBoltStyle.lightning,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.lightning,
        castArgb: 0xFFB8F0FF,
      ),

      aoeShape: AbilityAoeShape.chain,
    ),
    ClassAbilityDef(
      id: AbilityId.thunderstorm,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Thunderstorm',
      shortLabel: 'TStorm',
      description: 'Knock / AoE around self.',
      unlockLevel: 9,
      cooldown: 14,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.38,
      aoeShape: AbilityAoeShape.rain,
    ),
    ClassAbilityDef(
      id: AbilityId.earthquake,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Earthquake',
      shortLabel: 'Quake',
      description: 'Shake the ground under a stacked pack.',
      unlockLevel: 10,
      cooldown: 11,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.26,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFFC8A060,
        groundDisc: true,
        groundLife: 4.5,
        groundArgb: 0x66C09040,
        groundRadius: 3.0,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 3),
    ),
    ClassAbilityDef(
      id: AbilityId.elementalMastery,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Elemental Mastery',
      shortLabel: 'EM',
      description: 'Self haste buff.',
      unlockLevel: 11,
      cooldown: 35,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.earthShock,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Earth Shock',
      shortLabel: 'EShock',
      description: 'Signature interrupt hit.',
      unlockLevel: 11,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.4,
      boltStyle: SpellBoltStyle.lightning,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.lightning,
        castArgb: 0xFFB8F0FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.astralShift,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.elemental,
      name: 'Astral Shift',
      shortLabel: 'Shift',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— enhancement ——
    ClassAbilityDef(
      id: AbilityId.enhancementWeapons,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Enhanced Weapons',
      shortLabel: 'DualW',
      description: 'Always on: melee power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.26,
    ),
    ClassAbilityDef(
      id: AbilityId.stormstrike,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Stormstrike',
      shortLabel: 'StormS',
      description: 'Twin nature strike.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.35,
      boltStyle: SpellBoltStyle.lightning,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.lightning,
        castArgb: 0xFF90E8FF,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.lavaLash,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Lava Lash',
      shortLabel: 'Lash',
      description: 'Off-hand fire smash.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.25,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF7040,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.fireNova,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Fire Nova',
      shortLabel: 'FNova',
      description: 'AoE fire pulse.',
      unlockLevel: 7,
      cooldown: 9,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.50,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF8040,
        groundDisc: true,
        groundArgb: 0x88FF6030,
        groundLife: 2.0,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.magmaTotem,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Magma Totem',
      shortLabel: 'Magma',
      description: 'Drop a fire patch under the pack.',
      unlockLevel: 8,
      cooldown: 12,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.48,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF7030,
        groundDisc: true,
        groundLife: 4.0,
        groundArgb: 0x66FF6020,
        groundRadius: 2.7,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 3),
    ),
    ClassAbilityDef(
      id: AbilityId.feralSpirit,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Feral Spirit',
      shortLabel: 'Spirits',
      description: 'Summon two spirit wolves.',
      unlockLevel: 9,
      cooldown: 35,
      resourceCost: 15,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,
      summonCount: 2,
      summonDuration: 30,
      summonAtkScale: 0.42,
      summonName: 'Spirit Wolf',
      summonIdPrefix: 'wolf',
    ),
    ClassAbilityDef(
      id: AbilityId.frostShock,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Frost Shock',
      shortLabel: 'FrShock',
      description: 'Root nearest foe.',
      unlockLevel: 11,
      cooldown: 12,
      resourceCost: 12,
      effect: AbilityEffectKind.root,
      tier: AbilityCastTier.filler,
    ),
    ClassAbilityDef(
      id: AbilityId.shamanisticRage,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Shamanistic Rage',
      shortLabel: 'ShaRage',
      description: 'Grant resource + DR.',
      unlockLevel: 11,
      cooldown: 30,
      effect: AbilityEffectKind.grantResource,
      tier: AbilityCastTier.signature,
      coeff: 30,
      boltStyle: SpellBoltStyle.lightning,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.lightning,
        castArgb: 0xFFFF9040,
      ),

      customId: AbilityCustomId.shamanisticRage,
    ),
    ClassAbilityDef(
      id: AbilityId.enhancementAstral,
      gearAffinity: HeroRole.rogue,
      specId: HeroSpecId.enhancement,
      name: 'Astral Shift',
      shortLabel: 'Shift',
      description: 'Emergency DR.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— restorationShaman ——
    ClassAbilityDef(
      id: AbilityId.ancestralAwakening,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Ancestral Awakening',
      shortLabel: 'Awake',
      description: 'Always on: heal amplify.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveHealMul: 1.32,
    ),
    ClassAbilityDef(
      id: AbilityId.riptide,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Riptide',
      shortLabel: 'RTide',
      description: 'HoT-style heal.',
      unlockLevel: 3,
      cooldown: 5.5,
      resourceCost: 14,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.15,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF60E0A0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.healingWave,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Healing Wave',
      shortLabel: 'Wave',
      description: 'Solid single heal.',
      unlockLevel: 5,
      cooldown: 5,
      resourceCost: 18,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
      castDelaySeconds: 1.6,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D070,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.chainHeal,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Chain Heal',
      shortLabel: 'CHeal',
      description: 'Bounce heal pulse.',
      unlockLevel: 7,
      cooldown: 7,
      resourceCost: 24,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.35,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D070,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.earthShield,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Earth Shield',
      shortLabel: 'EShield',
      description: 'Absorb on lowest ally.',
      unlockLevel: 9,
      cooldown: 10,
      resourceCost: 20,
      effect: AbilityEffectKind.absorb,
      tier: AbilityCastTier.filler,
      coeff: 1.4,
    ),
    ClassAbilityDef(
      id: AbilityId.healingRain,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Healing Rain',
      shortLabel: 'Rain',
      description: 'AoE ally heal.',
      unlockLevel: 11,
      cooldown: 12,
      resourceCost: 28,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.filler,
      coeff: 1.1,
    ),
    ClassAbilityDef(
      id: AbilityId.spiritLink,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Spirit Link',
      shortLabel: 'SLink',
      description: 'Signature party mend.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 25,
      effect: AbilityEffectKind.heal,
      tier: AbilityCastTier.signature,
      coeff: 1.85,
      boltStyle: SpellBoltStyle.nature,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.nature,
        castArgb: 0xFF70D070,
        groundDisc: true,
        groundLife: 3.0,
        groundArgb: 0x6670D070,
        groundRadius: 2.8,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.natureSwiftness,
      gearAffinity: HeroRole.healer,
      specId: HeroSpecId.restorationShaman,
      name: 'Nature\'s Swiftness',
      shortLabel: 'SSwift',
      description: 'Emergency big heal.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyHeal,
      tier: AbilityCastTier.emergency,
      coeff: 2.2,
    ),
];
