// Warlock kits (Affliction / Demonology / Destruction)
part of '../class_ability.dart';

const List<ClassAbilityDef> _warlockKit = <ClassAbilityDef>[
    // —— affliction ——
    ClassAbilityDef(
      id: AbilityId.soulSiphon,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Soul Siphon',
      shortLabel: 'Siphon',
      description: 'Always on: drain lean.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.14,
      passiveHealMul: 1.08,
    ),
    ClassAbilityDef(
      id: AbilityId.corruption,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Corruption',
      shortLabel: 'Corr',
      description: 'Seed a lingering shadow DoT bolt.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 12,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.05,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF6B2D8A,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.unstableAffliction,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Unstable Affliction',
      shortLabel: 'UA',
      description: 'Heavy affliction surge — keep it rolling.',
      unlockLevel: 5,
      cooldown: 7,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.38,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8B3AA8,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.haunt,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Haunt',
      shortLabel: 'Haunt',
      description: 'Ghostly shadow nuke that answers your DoTs.',
      unlockLevel: 7,
      cooldown: 8,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.38,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF4A1A66,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.drainLife,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Drain Life',
      shortLabel: 'Drain',
      description: 'Siphon shadow damage into a self heal.',
      unlockLevel: 9,
      cooldown: 6,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.05,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF5C2878,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.curseOfAgony,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Curse of Agony',
      shortLabel: 'Agony',
      description: 'Mark the target for sustained shadow pain.',
      unlockLevel: 11,
      cooldown: 9,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.12,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF7030A0,
      ),

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.seedOfCorruption,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Seed of Corruption',
      shortLabel: 'Seed',
      description: 'Plant a shadow seed that bursts across the pack.',
      unlockLevel: 9,
      cooldown: 10,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.76,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8040B0,
        groundDisc: true,
        groundLife: 2.0,
        groundArgb: 0x668030A0,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.hauntBurst,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Haunt Burst',
      shortLabel: 'DotPop',
      description: 'Signature shadow finisher.',
      unlockLevel: 11,
      cooldown: 18,
      resourceCost: 28,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.75,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.soulburn,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.affliction,
      name: 'Soulburn',
      shortLabel: 'SBurn',
      description: 'Emergency self shield.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— demonology ——
    ClassAbilityDef(
      id: AbilityId.demonicKnowledge,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Demonic Knowledge',
      shortLabel: 'Know',
      description: 'Always on: pet lean + haste.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 0.96,
      passiveHasteMul: 1.06,
    ),
    ClassAbilityDef(
      id: AbilityId.shadowBolt,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Shadow Bolt',
      shortLabel: 'SBolt',
      description: 'Core shadow bolt.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.95,
      castDelaySeconds: 1.5,
    ),
    ClassAbilityDef(
      id: AbilityId.handOfGuldan,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Hand of Gul\'dan',
      shortLabel: 'Guldan',
      description: 'Fel AoE smash.',
      unlockLevel: 5,
      cooldown: 8,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.78,
      boltStyle: SpellBoltStyle.demon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.demon,
        castArgb: 0xFF70FF40,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.hellfire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Hellfire',
      shortLabel: 'Hellfire',
      description: 'Fel fire around you when the pack is stacked.',
      unlockLevel: 8,
      cooldown: 10,
      resourceCost: 14,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.58,
      boltStyle: SpellBoltStyle.demon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.demon,
        castArgb: 0xFF80FF40,
        groundDisc: true,
        groundLife: 3.0,
        groundArgb: 0x6680C030,
        groundRadius: 2.7,
      ),
      aoeShape: AbilityAoeShape.ground,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.immolateDemo,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Immolate',
      shortLabel: 'Immo',
      description: 'Fire DoT hit.',
      unlockLevel: 7,
      cooldown: 6,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.98,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.metamorphosis,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Metamorphosis',
      shortLabel: 'Meta',
      description: 'Demon form — hit harder.',
      unlockLevel: 9,
      cooldown: 45,
      resourceCost: 25,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFF8040C0,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.demonCharge,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Demon Charge',
      shortLabel: 'DCharge',
      description: 'Close / haste burst.',
      unlockLevel: 11,
      cooldown: 16,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.chaosBoltDemo,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Chaos Bolt',
      shortLabel: 'DChaos',
      description: 'Heavy chaos nuke.',
      unlockLevel: 11,
      cooldown: 10,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.62,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF5020),
    ),
    ClassAbilityDef(
      id: AbilityId.sacrifice,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.demonology,
      name: 'Demonic Sacrifice',
      shortLabel: 'DSac',
      description: 'Emergency absorb.',
      unlockLevel: 12,
      cooldown: 55,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),

    // —— destruction ——
    ClassAbilityDef(
      id: AbilityId.cataclysm,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Cataclysm',
      shortLabel: 'Cata',
      description: 'Always on: fire power.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.06,
    ),
    ClassAbilityDef(
      id: AbilityId.incinerate,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Incinerate',
      shortLabel: 'Incin',
      description: 'Core fire bolt.',
      unlockLevel: 3,
      cooldown: 5,
      resourceCost: 14,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.00,
    ),
    ClassAbilityDef(
      id: AbilityId.conflagrate,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Conflagrate',
      shortLabel: 'Conflag',
      description: 'Burst fire hit.',
      unlockLevel: 5,
      cooldown: 6,
      resourceCost: 18,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.16,
    ),
    ClassAbilityDef(
      id: AbilityId.immolateDestro,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Immolate',
      shortLabel: 'Immo',
      description: 'DoT fire mark.',
      unlockLevel: 7,
      cooldown: 7,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.80,

      gate: AbilityGate(maintainDot: true),
    ),
    ClassAbilityDef(
      id: AbilityId.rainOfFire,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Rain of Fire',
      shortLabel: 'FRain',
      description: 'Fire rain on the pack around your focus.',
      unlockLevel: 8,
      cooldown: 8,
      resourceCost: 16,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.62,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.fire,
        castArgb: 0xFFFF6030,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x88FF5020,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.shadowfury,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Shadowfury',
      shortLabel: 'SFury',
      description: 'AoE stun pulse.',
      unlockLevel: 9,
      cooldown: 16,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.7,
      boltStyle: SpellBoltStyle.shadow,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.shadow,
        castArgb: 0xFFB060E0,
        groundDisc: true,
        groundLife: 1.4,
        groundArgb: 0x88A040D0,
        groundRadius: 3.0,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.backdraft,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Backdraft',
      shortLabel: 'BDraft',
      description: 'Self haste buff.',
      unlockLevel: 11,
      cooldown: 25,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.chaosBolt,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Chaos Bolt',
      shortLabel: 'Chaos',
      description: 'Signature chaos nuke.',
      unlockLevel: 11,
      cooldown: 10,
      resourceCost: 22,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 1.45,
      castDelaySeconds: 2.0,
      boltStyle: SpellBoltStyle.fire,
      vfx: AbilityVfxSpec(boltStyle: SpellBoltStyle.fire, castArgb: 0xFFFF5020),
    ),
    ClassAbilityDef(
      id: AbilityId.shadowWard,
      gearAffinity: HeroRole.mage,
      specId: HeroSpecId.destruction,
      name: 'Shadow Ward',
      shortLabel: 'SWard',
      description: 'Emergency absorb.',
      unlockLevel: 12,
      cooldown: 50,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
];
