// Warrior kits (Protection / Arms / Fury)
part of '../class_ability.dart';

const List<ClassAbilityDef> _warriorKit = <ClassAbilityDef>[
    // —— Warrior (Protection) ——
    ClassAbilityDef(
      id: AbilityId.defensiveStance,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Defensive Stance',
      shortLabel: 'Guard',
      description:
          'Extra guard DEF, stronger aggro, slightly less damage dealt.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 0.9,
      passiveInMul: 0.92,
    ),
    ClassAbilityDef(
      id: AbilityId.charge,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Charge',
      shortLabel: 'Charge',
      description:
          'Rush a foe in line of sight (not too far) and briefly root them.',
      unlockLevel: 4,
      cooldown: 12,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.charge,
      gate: AbilityGate(
        requireFocus: true,
        minRange: 3.5,
        maxRange: 8.0,
        needClearCorridor: true,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.shieldBlock,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Shield Block',
      shortLabel: 'Block',
      description: 'Damage reduction window. Enables Revenge. Requires shield.',
      unlockLevel: 3,
      cooldown: 8,
      resourceCost: 15,
      requiresShield: true,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,
      coeff: 0.35,

      customId: AbilityCustomId.shieldBlock,
      gate: AbilityGate(requireFocus: true, maxRange: 3.2),
    ),
    ClassAbilityDef(
      id: AbilityId.thunderClap,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Thunder Clap',
      shortLabel: 'Clap',
      description: 'AoE smash that slows enemy attacks.',
      unlockLevel: 5,
      cooldown: 7,
      resourceCost: 20,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.55,
      boltStyle: SpellBoltStyle.lightning,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.lightning,
        castArgb: 0xFFA0E8FF,
      ),

      customId: AbilityCustomId.thunderClap,
      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.devastate,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Devastate',
      shortLabel: 'Sunder',
      description: 'Strike that applies Sunder Armor stacks.',
      unlockLevel: 6,
      cooldown: 2.8,
      resourceCost: 15,
      requiresShield: true,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.55,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFE08A,
      ),

      customId: AbilityCustomId.devastate,
      gate: AbilityGate(
        requireFocus: true,
        maxRangePad: 0.35,
        sunderRefresh: true,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.taunt,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Taunt',
      shortLabel: 'Taunt',
      description: 'Force a loose enemy to attack you.',
      unlockLevel: 7,
      cooldown: 10,
      effect: AbilityEffectKind.taunt,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.tauntPull,
    ),
    ClassAbilityDef(
      id: AbilityId.demoralizingShout,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Demoralizing Shout',
      shortLabel: 'Demo',
      description: 'Weaken nearby enemies\' attack power.',
      unlockLevel: 8,
      cooldown: 12,
      resourceCost: 18,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.2,

      customId: AbilityCustomId.demoralizingShout,
      aoeShape: AbilityAoeShape.nova,
      gate: AbilityGate(nearbyRadius: 3.4),
    ),
    ClassAbilityDef(
      id: AbilityId.shieldSlam,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Shield Slam',
      shortLabel: 'SSlam',
      description: 'Heavy shield bash. Requires shield.',
      unlockLevel: 9,
      cooldown: 5.5,
      resourceCost: 25,
      requiresShield: true,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.1,

      fireMode: AbilityFireMode.swingRider,
      customId: AbilityCustomId.shieldSlam,
      gate: AbilityGate(requireFocus: true, notQueued: true),
    ),
    ClassAbilityDef(
      id: AbilityId.commandingShout,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Commanding Shout',
      shortLabel: 'Shout',
      description: 'Rally the party — mild damage buff for a short window.',
      unlockLevel: 10,
      cooldown: 30,
      resourceCost: 12,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      customId: AbilityCustomId.commandingShout,
      gate: AbilityGate(requireFocus: true, atkShoutRefresh: true),
    ),
    ClassAbilityDef(
      id: AbilityId.revenge,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Revenge',
      shortLabel: 'Revenge',
      description: 'After blocking, next attack hits much harder.',
      unlockLevel: 11,
      cooldown: 0,
      resourceCost: 5,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,

      fireMode: AbilityFireMode.onBlock,
    ),
    ClassAbilityDef(
      id: AbilityId.shockwave,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Shockwave',
      shortLabel: 'SWave',
      description: 'Cone smash — AoE damage and stun.',
      unlockLevel: 11,
      cooldown: 16,
      resourceCost: 22,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 0.9,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFC070,
        groundDisc: true,
        groundLife: 1.6,
        groundArgb: 0x88FFE08A,
        groundRadius: 2.4,
      ),

      customId: AbilityCustomId.shockwave,
      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.lastStand,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Last Stand',
      shortLabel: 'Stand',
      description: 'Emergency temporary bonus health.',
      unlockLevel: 12,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.lastStand,
      gate: AbilityGate(casterHpMax: 0.4),
    ),
    ClassAbilityDef(
      id: AbilityId.shieldWall,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.protection,
      name: 'Shield Wall',
      shortLabel: 'Wall',
      description: 'Massive damage reduction. Requires shield.',
      unlockLevel: 12,
      cooldown: 60,
      requiresShield: true,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,

      customId: AbilityCustomId.shieldWall,
      gate: AbilityGate(casterHpMax: 0.28),
    ),

    // —— arms ——
    ClassAbilityDef(
      id: AbilityId.armsStance,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Battle Stance',
      shortLabel: 'BStance',
      description: 'Always on: stronger attacks, less guard.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 2.02,
      passiveInMul: 1.04,
    ),
    ClassAbilityDef(
      id: AbilityId.mortalStrike,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Mortal Strike',
      shortLabel: 'Mortal',
      description: 'Heavy single-target strike.',
      unlockLevel: 3,
      cooldown: 3.0,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 2.35,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFC070,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.overpower,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Overpower',
      shortLabel: 'Over',
      description: 'Quick follow-up slash.',
      unlockLevel: 5,
      cooldown: 3.5,
      resourceCost: 16,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.58,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFE08A,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.rend,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Rend',
      shortLabel: 'Rend',
      description: 'Bleed the nearest foe.',
      unlockLevel: 7,
      cooldown: 6,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 0.9,
    ),
    ClassAbilityDef(
      id: AbilityId.sweepingStrikes,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Sweeping Strikes',
      shortLabel: 'Sweep',
      description: 'Your strikes cleave nearby foes for a few seconds.',
      unlockLevel: 9,
      cooldown: 18,
      resourceCost: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.cleave,
      selfBuffDuration: 7,
      gate: AbilityGate(packMin: 2),
    ),
    ClassAbilityDef(
      id: AbilityId.bladestorm,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Bladestorm',
      shortLabel: 'BStorm',
      description: 'Spinning AoE carnage.',
      unlockLevel: 11,
      cooldown: 38,
      resourceCost: 25,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.signature,
      coeff: 0.46,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFD070,
        groundDisc: true,
        groundLife: 3.2,
        groundArgb: 0x88FFE08A,
        groundRadius: 2.8,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.armsExecute,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Execute',
      shortLabel: 'Exec',
      description: 'Finisher on wounded foes.',
      unlockLevel: 11,
      cooldown: 6.5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 3.45,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFB050,
      ),

      gate: AbilityGate(executeHpFrac: 0.25),
    ),
    ClassAbilityDef(
      id: AbilityId.armsRally,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.arms,
      name: 'Rallying Cry',
      shortLabel: 'Rally',
      description: 'Emergency party absorb.',
      unlockLevel: 12,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
      coeff: 1.0,
    ),

    // —— fury ——
    ClassAbilityDef(
      id: AbilityId.berserkerStance,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Berserker Stance',
      shortLabel: 'ZStance',
      description: 'Always on: haste at a cost.',
      unlockLevel: 1,
      cooldown: 0,
      showInHud: true,
      effect: AbilityEffectKind.passive,
      tier: AbilityCastTier.passive,
      passiveOutMul: 1.7,
      passiveHasteMul: 1.12,
      passiveInMul: 1.06,
    ),
    ClassAbilityDef(
      id: AbilityId.bloodthirst,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Bloodthirst',
      shortLabel: 'Thirst',
      description: 'Strike that returns rage on hit.',
      unlockLevel: 3,
      cooldown: 4.5,
      resourceCost: 20,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.3,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF6060,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.whirlwind,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Whirlwind',
      shortLabel: 'Whirl',
      description: 'Spin attack around you.',
      unlockLevel: 5,
      cooldown: 7,
      resourceCost: 16,
      effect: AbilityEffectKind.aoe,
      tier: AbilityCastTier.filler,
      coeff: 0.60,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFFE08A,
        groundDisc: true,
        groundLife: 2.5,
        groundArgb: 0x88FFE08A,
      ),

      aoeShape: AbilityAoeShape.ground,
    ),
    ClassAbilityDef(
      id: AbilityId.ragingBlow,
      boltStyle: SpellBoltStyle.weapon,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Slam',
      shortLabel: 'Blow',
      description: 'Heavy rage strike.',
      unlockLevel: 7,
      cooldown: 4.5,
      resourceCost: 15,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.filler,
      coeff: 1.55,
    ),
    ClassAbilityDef(
      id: AbilityId.enrageBuff,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Enrage',
      shortLabel: 'Enrage',
      description: 'Self haste window.',
      unlockLevel: 9,
      cooldown: 20,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.haste,
    ),
    ClassAbilityDef(
      id: AbilityId.deathWish,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Death Wish',
      shortLabel: 'DWish',
      description: 'Signature damage window — hit harder, take more.',
      unlockLevel: 11,
      cooldown: 40,
      resourceCost: 10,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.signature,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF7070,
      ),

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
    ClassAbilityDef(
      id: AbilityId.furyExecute,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Rampage',
      shortLabel: 'Rampage',
      description: 'Burst flurry — not waiting for a low target.',
      unlockLevel: 11,
      cooldown: 10,
      resourceCost: 25,
      effect: AbilityEffectKind.damage,
      tier: AbilityCastTier.signature,
      coeff: 2.1,
      boltStyle: SpellBoltStyle.weapon,
      vfx: AbilityVfxSpec(
        boltStyle: SpellBoltStyle.weapon,
        castArgb: 0xFFFF9050,
      ),
    ),
    ClassAbilityDef(
      id: AbilityId.enragedRegeneration,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Enraged Regeneration',
      shortLabel: 'EReg',
      description: 'Emergency heal + DR while fighting.',
      unlockLevel: 12,
      cooldown: 45,
      effect: AbilityEffectKind.emergencyDefend,
      tier: AbilityCastTier.emergency,
    ),
    ClassAbilityDef(
      id: AbilityId.furyRecklessness,
      gearAffinity: HeroRole.warrior,
      specId: HeroSpecId.fury,
      name: 'Recklessness',
      shortLabel: 'Reck',
      description: 'All-in damage window — not a panic wall.',
      unlockLevel: 12,
      cooldown: 50,
      resourceCost: 25,
      effect: AbilityEffectKind.selfBuff,
      tier: AbilityCastTier.filler,

      selfBuffKind: AbilitySelfBuffKind.amp,
      selfBuffDuration: 8,
    ),
];
